const masterWorkbookRuntimeFiles = [
  "./package.json",
  "./src/masters/bulk-xlsx*.js",
  "./src/masters/bulk-csv.js",
  "./src/auth/errors.js",
  "./node_modules/@fast-csv/format/**/*",
  "./node_modules/@fast-csv/parse/**/*",
  "./node_modules/@types/node/**/*",
  "./node_modules/archiver-utils/**/*",
  "./node_modules/archiver-utils/node_modules/isarray/**/*",
  "./node_modules/archiver-utils/node_modules/readable-stream/**/*",
  "./node_modules/archiver-utils/node_modules/safe-buffer/**/*",
  "./node_modules/archiver-utils/node_modules/string_decoder/**/*",
  "./node_modules/archiver/**/*",
  "./node_modules/async/**/*",
  "./node_modules/balanced-match/**/*",
  "./node_modules/base64-js/**/*",
  "./node_modules/big-integer/**/*",
  "./node_modules/binary/**/*",
  "./node_modules/bl/**/*",
  "./node_modules/bluebird/**/*",
  "./node_modules/brace-expansion/**/*",
  "./node_modules/buffer-crc32/**/*",
  "./node_modules/buffer-indexof-polyfill/**/*",
  "./node_modules/buffer/**/*",
  "./node_modules/buffers/**/*",
  "./node_modules/chainsaw/**/*",
  "./node_modules/compress-commons/**/*",
  "./node_modules/concat-map/**/*",
  "./node_modules/core-util-is/**/*",
  "./node_modules/crc-32/**/*",
  "./node_modules/crc32-stream/**/*",
  "./node_modules/dayjs/**/*",
  "./node_modules/duplexer2/**/*",
  "./node_modules/duplexer2/node_modules/isarray/**/*",
  "./node_modules/duplexer2/node_modules/readable-stream/**/*",
  "./node_modules/duplexer2/node_modules/safe-buffer/**/*",
  "./node_modules/duplexer2/node_modules/string_decoder/**/*",
  "./node_modules/end-of-stream/**/*",
  "./node_modules/exceljs/**/*",
  "./node_modules/fast-csv/**/*",
  "./node_modules/fs-constants/**/*",
  "./node_modules/fs.realpath/**/*",
  "./node_modules/fstream/**/*",
  "./node_modules/glob/**/*",
  "./node_modules/graceful-fs/**/*",
  "./node_modules/ieee754/**/*",
  "./node_modules/immediate/**/*",
  "./node_modules/inflight/**/*",
  "./node_modules/inherits/**/*",
  "./node_modules/jszip/**/*",
  "./node_modules/jszip/node_modules/isarray/**/*",
  "./node_modules/jszip/node_modules/readable-stream/**/*",
  "./node_modules/jszip/node_modules/safe-buffer/**/*",
  "./node_modules/jszip/node_modules/string_decoder/**/*",
  "./node_modules/lazystream/**/*",
  "./node_modules/lazystream/node_modules/isarray/**/*",
  "./node_modules/lazystream/node_modules/readable-stream/**/*",
  "./node_modules/lazystream/node_modules/safe-buffer/**/*",
  "./node_modules/lazystream/node_modules/string_decoder/**/*",
  "./node_modules/lie/**/*",
  "./node_modules/listenercount/**/*",
  "./node_modules/lodash.defaults/**/*",
  "./node_modules/lodash.difference/**/*",
  "./node_modules/lodash.escaperegexp/**/*",
  "./node_modules/lodash.flatten/**/*",
  "./node_modules/lodash.groupby/**/*",
  "./node_modules/lodash.isboolean/**/*",
  "./node_modules/lodash.isequal/**/*",
  "./node_modules/lodash.isfunction/**/*",
  "./node_modules/lodash.isnil/**/*",
  "./node_modules/lodash.isplainobject/**/*",
  "./node_modules/lodash.isundefined/**/*",
  "./node_modules/lodash.union/**/*",
  "./node_modules/lodash.uniq/**/*",
  "./node_modules/minimatch/**/*",
  "./node_modules/minimist/**/*",
  "./node_modules/mkdirp/**/*",
  "./node_modules/normalize-path/**/*",
  "./node_modules/once/**/*",
  "./node_modules/pako/**/*",
  "./node_modules/path-is-absolute/**/*",
  "./node_modules/pend/**/*",
  "./node_modules/process-nextick-args/**/*",
  "./node_modules/readable-stream/**/*",
  "./node_modules/readdir-glob/**/*",
  "./node_modules/readdir-glob/node_modules/brace-expansion/**/*",
  "./node_modules/readdir-glob/node_modules/minimatch/**/*",
  "./node_modules/rimraf/**/*",
  "./node_modules/safe-buffer/**/*",
  "./node_modules/saxes/**/*",
  "./node_modules/setimmediate/**/*",
  "./node_modules/string_decoder/**/*",
  "./node_modules/tar-stream/**/*",
  "./node_modules/tmp/**/*",
  "./node_modules/traverse/**/*",
  "./node_modules/unzipper/**/*",
  "./node_modules/unzipper/node_modules/isarray/**/*",
  "./node_modules/unzipper/node_modules/readable-stream/**/*",
  "./node_modules/unzipper/node_modules/safe-buffer/**/*",
  "./node_modules/unzipper/node_modules/string_decoder/**/*",
  "./node_modules/util-deprecate/**/*",
  "./node_modules/uuid/**/*",
  "./node_modules/wrappy/**/*",
  "./node_modules/xmlchars/**/*",
  "./node_modules/yauzl/**/*",
  "./node_modules/zip-stream/**/*",
  "./node_modules/zip-stream/node_modules/archiver-utils/**/*"
];

const userOptionRuntimeFiles = [
  './node_modules/{react-select,react,react-dom,react-is,memoize-one,hoist-non-react-statics,stylis,use-isomorphic-layout-effect}/**/*',
  './node_modules/@babel/runtime/**/*', './node_modules/@emotion/**/*', './node_modules/@floating-ui/**/*',
];

const nextConfig = {
  poweredByHeader: false,
  reactProductionProfiling: process.env.PROFILE_REACT === '1',
  experimental: { optimizePackageImports: ['@tabler/icons-react'] },
  outputFileTracingIncludes: {
    '/api/master-bulk{,/**}': masterWorkbookRuntimeFiles,
    // The Node-only user filter loads this existing dependency graph at runtime.
    '/api/users{,/**}': userOptionRuntimeFiles,
    '/api/masters/{products,test-parameters,methods}/custom-field-users': userOptionRuntimeFiles,
    '/api/organization-settings/module-access/options': userOptionRuntimeFiles,
    '/api/masters/{products,test-parameters,methods}/custom-field-generation': ['./package.json', './src/custom-fields/*.js', './src/masters/custom-field-config.js', './src/auth/errors.js',
      './node_modules/moment/**', './node_modules/moment-timezone/**'],
    '/api/users/custom-fields/generate': ['./package.json', './src/custom-fields/*.js', './src/masters/custom-field-config.js', './src/auth/errors.js',
      './node_modules/moment/**', './node_modules/moment-timezone/**'],
  },
  async headers() {
    // Next 16.3.4 appends Route Handler Content-Type as an array, which its
    // compression filter rejects. Setting these JSON-only routes here keeps a
    // scalar header and the framework's normal encoding negotiation/threshold.
    // Upstream: https://github.com/vercel/next.js/issues/98007
    return [{
      source: '/:path*',
      headers: [
        { key: 'X-Content-Type-Options', value: 'nosniff' },
        { key: 'Referrer-Policy', value: 'same-origin' },
        { key: 'X-Frame-Options', value: 'DENY' },
      ],
    }, ...[
      '/api/templates', '/api/templates/:templateId',
      '/api/template-versions/:versionId', '/api/template-versions/:versionId/:action(freeze|draft)',
      '/api/datasheets/:datasheetId', '/api/datasheets/:datasheetId/:action(values|calculate|repeats|submit)',
      '/api/samples', '/api/samples/:sampleId', '/api/samples/:sampleId/test-requests',
      '/api/samples/:sampleId/:action(reports|report-options)', '/api/reports/:reportId', '/api/reports/:reportId/pdf',
      '/api/test-requests/:requestId', '/api/test-requests/:requestId/:action(assignments|allocation-options)',
      '/api/workflow-runs/:runId', '/api/workflow-runs/:runId/:action(transitions|datasheet-transitions)',
      '/api/approvals/:caseId', '/api/approval-assignments/:assignmentId/approve',
      '/api/report-assets/documents', '/api/report-assets/documents/:documentId',
      '/api/report-assets/watermarks', '/api/report-assets/watermarks/:watermarkId',
      '/api/report-assets/custom-css', '/api/report-assets/custom-css/current',
    ].map((source) => ({ source, headers: [{ key: 'Content-Type', value: 'application/json; charset=utf-8' }] }))];
  },
};

export default nextConfig;
