import { test, expect } from '@playwright/test';
import { ownerPool, createAccount } from '../helpers/database.js';
import { createLaboratoryFixture } from '../helpers/laboratory.js';
import { prepareSubjectJob } from '../helpers/job-subjects.js';
import { createReportTemplate } from '../helpers/reports.js';
import { registerSample } from '../../src/samples/register.js';
import { generateTestRequests } from '../../src/test-requests/generate.js';
import { signIn, withSession } from '../../src/auth/service.js';
import { closePool } from '../../src/db/pool.js';

let owner;
test.beforeAll(() => { owner = ownerPool(); });
test.afterAll(async () => { await closePool(); await owner.end(); });

test('source settings and job selection preserve failed choices and create one assigned job per product line', async ({ page, context }, testInfo) => {
  test.setTimeout(60_000);
  const user = await createAccount(owner, { permissions: ['samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute', 'templates.manage', 'settings.manage'] });
  const session = await signIn({ identifier: user.username, password: user.password });
  const work = (callback) => withSession(session.token, callback, { csrfToken: session.csrfToken });
  const fixture = await createLaboratoryFixture(owner, user, { repeated: false });
  const sample = await work((client, identity) => registerSample(client, identity, { ...fixture.registration,
    products: [fixture.registration.products[0], structuredClone(fixture.registration.products[0])] }));
  const generated = await work((client, identity) => generateTestRequests(client, identity, sample.id));
  const pageErrors = []; page.on('pageerror', (error) => pageErrors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/login');
  await page.getByLabel('Username', { exact: true }).fill(user.username);
  await page.getByLabel('Password', { exact: true }).fill(user.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/me$/);
  await page.goto('/organization_settings');
  const template = page.getByRole('combobox', { name: 'Job Template', exact: true });
  await template.selectOption(fixture.template.templateId);
  const settingsRoute = '**/api/organization-settings/laboratory';
  await page.route(settingsRoute, (route) => route.request().method() === 'PUT'
    ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic settings interruption' } }) }) : route.continue());
  await page.getByRole('button', { name: 'Save Settings', exact: true }).click();
  await expect(page.locator('.settings-layout').getByRole('alert')).toContainText('Synthetic settings interruption');
  await expect(template).toHaveValue(fixture.template.templateId);
  await page.getByRole('tab', { name: 'Workflow Configs', exact: true }).click();
  const workflowId = fixture.workflowRecords.find((record) => record.workflow.appliesTo === 'test_request').workflow.id;
  await page.getByRole('combobox', { name: 'Job Workflow', exact: true }).selectOption(workflowId);
  await page.unroute(settingsRoute);
  const saved = page.waitForResponse((response) => response.url().endsWith('/api/organization-settings/laboratory') && response.request().method() === 'PUT');
  await page.getByRole('button', { name: 'Save Settings', exact: true }).click();
  expect((await saved).status()).toBe(200);
  await page.reload();
  await expect(template).toHaveValue(fixture.template.templateId);
  await page.getByRole('tab', { name: 'Workflow Configs', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Job Workflow', exact: true })).toHaveValue(workflowId);
  await page.screenshot({ path: testInfo.outputPath('job-settings-desktop.png'), fullPage: true, animations: 'disabled' });
  const cookies = await context.cookies();
  const headers = { Origin: 'http://127.0.0.1:3100', 'X-CSRF-Token': cookies.find((cookie) => cookie.name === 'sampleify_csrf').value };
  expect((await page.request.put('/api/organization-settings/laboratory', { headers: { Origin: headers.Origin }, data: {
    revision: 1, autoCreateJobs: false, resultSummaryTemplateId: fixture.template.templateId, jobWorkflowId: workflowId } })).status()).toBe(403);
  await page.goto(`/samples/${sample.id}/test_requests`);
  await page.getByRole('button', { name: 'Create Job', exact: true }).click();
  await page.getByRole('button', { name: 'Create Job', exact: true }).click();
  await expect(page.getByText('Select assignee.', { exact: true })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Select all test requests', exact: true }).check();
  await page.getByRole('combobox', { name: 'Assignee:', exact: true }).fill('Synthetic Analyst');
  await page.getByRole('option', { name: 'Synthetic Analyst', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Reviewer:', exact: true })).toHaveCount(0);
  const jobRoute = '**/api/test-requests/jobs';
  await page.route(jobRoute, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic job interruption' } }) }));
  await page.getByRole('button', { name: 'Create Job', exact: true }).click();
  await expect(page.locator('.smplfy-tr-listing-page').getByRole('alert')).toContainText('Synthetic job interruption');
  for (const request of generated.items) await expect(page.getByRole('checkbox', { name: `Select ${request.requestNumber}`, exact: true })).toBeChecked();
  await expect(page.locator('.smplfy-tr-selection-card')).toContainText('Synthetic Analyst');
  await page.screenshot({ path: testInfo.outputPath('job-selection-desktop.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.lims-main')).toHaveCSS('margin-left', '0px');
  await page.screenshot({ path: testInfo.outputPath('job-selection-mobile.png'), fullPage: true, animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await page.request.post('/api/test-requests/jobs', { headers: { Origin: headers.Origin }, data: {
    requestIds: generated.items.map((request) => request.id), analystUserId: user.userId } })).status()).toBe(403);
  await page.unroute(jobRoute);
  const created = page.waitForResponse((response) => response.url().endsWith('/api/test-requests/jobs') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Create Job', exact: true }).click();
  const response = await created; expect(response.status()).toBe(201);
  const result = await response.json(); expect(result.items).toHaveLength(2);
  await expect(page.locator('.smplfy-tr-jobs-card')).toContainText('2 Jobs');
  await expect(page.locator('.smplfy-tr-selection-card')).toHaveCount(0);
  await expect(page.locator('.smplfy-tr-requests-card')).toContainText('0 Test Requests');
  await page.reload();
  for (const job of result.items) {
    await expect(page.getByRole('link', { name: job.requestNumber, exact: true })).toBeVisible();
    const request = await page.request.get(`/api/test-requests/${job.id}`).then((record) => record.json());
    expect(request.isJob).toBe(true); expect(request.assignments.find((assignment) => assignment.assignmentType === 'analyst').assignedUserId).toBe(user.userId);
  }
  expect(pageErrors).toEqual([]);
});

test('job parameter labels stay with separate values through measurement clones, failed saves and reload', async ({ page }, testInfo) => {
  test.setTimeout(60_000);
  const user = await createAccount(owner, { permissions: ['samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute', 'templates.manage', 'settings.manage'] });
  Object.assign(user, await signIn({ identifier: user.username, password: user.password }));
  const flow = await prepareSubjectJob(owner, user, user, { manualParent: true });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/login');
  await page.getByLabel('Username', { exact: true }).fill(user.username);
  await page.getByLabel('Password', { exact: true }).fill(user.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/me$/);
  const path = `/samples/${flow.sample.id}/data_sheets/${flow.job.datasheetId}`;
  await page.goto(path);
  const rows = page.locator(`[data-section-id="${flow.template.parameterSectionId}"]`);
  const inputs = page.getByRole('spinbutton', { name: 'raw_0', exact: true });
  await expect(rows).toHaveCount(4); await expect(inputs).toHaveCount(4);
  const before = await page.request.get(`/api/datasheets/${flow.job.datasheetId}`).then((response) => response.json());
  for (const occurrence of before.capture.occurrences.filter((row) => row.subject)) {
    await expect(page.locator(`[data-section-id="${flow.template.parameterSectionId}"][data-occurrence-id="${occurrence.id}"]`)).toContainText(occurrence.subject.parameterName);
  }
  for (let index = 0; index < 4; index += 1) await inputs.nth(index).fill(String(index * 2));
  await page.getByRole('button', { name: 'Calculate', exact: true }).click();
  await expect(page.getByLabel('result_0', { exact: true }).first()).toHaveText('0.00');
  await expect(page.getByLabel('result_0', { exact: true }).nth(3)).toHaveText('12.00');
  await page.getByRole('link', { name: 'Clone row with data', exact: true }).first().click();
  await expect(inputs).toHaveCount(6);
  const cloned = await page.request.get(`/api/datasheets/${flow.job.datasheetId}`).then((response) => response.json());
  const added = cloned.capture.occurrences.filter((row) => row.subject && !before.capture.occurrences.some((prior) => prior.id === row.id));
  expect(added).toHaveLength(2);
  const clonedRows = added.map((row) => page.locator(`[data-section-id="${flow.template.parameterSectionId}"][data-occurrence-id="${row.id}"]`));
  for (let index = 0; index < 2; index += 1) {
    await expect(clonedRows[index]).toContainText(added[index].subject.parameterName);
    await expect(clonedRows[index].getByRole('spinbutton', { name: 'raw_0', exact: true })).toHaveValue(String(index * 2));
  }
  const clonedInput = clonedRows[0].getByRole('spinbutton', { name: 'raw_0', exact: true });
  await page.screenshot({ path: testInfo.outputPath('job-parameters-desktop.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.lims-main')).toHaveCSS('margin-left', '0px');
  await page.screenshot({ path: testInfo.outputPath('job-parameters-mobile.png'), fullPage: true, animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const valuesRoute = `**/api/datasheets/${flow.job.datasheetId}/values`;
  await page.route(valuesRoute, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic parameter interruption' } }) }));
  await clonedInput.fill('9');
  await page.getByRole('button', { name: 'Calculate', exact: true }).click();
  await expect(page.locator('.tr-details-results-page').getByRole('alert')).toContainText('Synthetic parameter interruption');
  await expect(clonedInput).toHaveValue('9');
  await page.unroute(valuesRoute);
  await page.getByRole('button', { name: 'Retry save', exact: true }).click();
  await expect(page.locator('.tr-details-results-page').getByRole('alert')).toHaveCount(0);
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(page).toHaveURL(`/samples/${flow.sample.id}/test_requests/${flow.job.id}`);
  await page.getByRole('link', { name: 'Add Results', exact: true }).click();
  await expect(inputs).toHaveCount(6); await expect(clonedInput).toHaveValue('9');
  await expect(clonedRows[0].getByLabel('result_0', { exact: true })).toHaveText('18.00');
  const saved = await page.request.get(`/api/datasheets/${flow.job.datasheetId}`).then((response) => response.json());
  const subjects = saved.capture.occurrences.filter((row) => row.subject);
  expect(subjects).toHaveLength(6); expect(new Set(subjects.map((row) => row.subject.testRequestId))).toEqual(new Set(flow.requests.map((row) => row.id)));
  expect(saved.datasheet.status).toBe('in_progress'); expect(errors).toEqual([]);
});

test('source result defaults survive editor retries and record unchanged entries only after analyst blur', async ({ page }, testInfo) => {
  test.setTimeout(60_000);
  const user = await createAccount(owner, { permissions: ['samples.read', 'samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute', 'templates.read', 'templates.manage', 'settings.manage'] });
  Object.assign(user, await signIn({ identifier: user.username, password: user.password }));
  const flow = await prepareSubjectJob(owner, user, user, { resultWidget: true, resultValueType: 'result', resultDefaultValue: '000.00' });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/login');
  await page.getByLabel('Username', { exact: true }).fill(user.username);
  await page.getByLabel('Password', { exact: true }).fill(user.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/me$/);
  await page.goto(`/master_template_management/${flow.template.templateId}`);
  const definitionResponse = await page.request.get(`/api/templates/${flow.template.templateId}`);
  expect(definitionResponse.status()).toBe(200);
  const definition = await definitionResponse.json();
  const field = Object.values(definition.model.fieldsById).find((item) => item.widget === 'result_widget');
  const column = page.locator(`[data-col-id="${field.columnId}"]`);
  const dialog = page.getByRole('dialog', { name: 'Widget Configuration', exact: true });
  async function openDefaults() {
    await page.getByRole('button', { name: 'Edit Mode Off', exact: true }).click();
    await column.locator('.action-dropdown-toggle').click();
    await page.getByRole('menuitem', { name: 'Widget', exact: true }).click();
  }
  await openDefaults();
  await expect(dialog.getByLabel('Default Value', { exact: true })).toHaveValue('000.00');
  await expect(dialog).toContainText('Use "-" to keep this default as blank / null.');
  await dialog.getByLabel('Default Value', { exact: true }).fill('Not detected');
  await dialog.getByLabel('Placeholder', { exact: true }).fill('Enter observed result');
  const templateRoute = `**/api/template-versions/${flow.template.versionId}`;
  await page.route(templateRoute, (route) => route.request().method() === 'PATCH'
    ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic default editor interruption' } }) }) : route.continue());
  await dialog.getByRole('button', { name: 'Update data', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Synthetic default editor interruption' })).toBeVisible();
  await expect(dialog.getByLabel('Default Value', { exact: true })).toHaveValue('Not detected');
  await page.screenshot({ path: testInfo.outputPath('result-default-editor-desktop.png'), fullPage: true, animations: 'disabled' });
  await page.unroute(templateRoute);
  await dialog.getByRole('button', { name: 'Update data', exact: true }).click(); await expect(dialog).toBeHidden();
  await page.reload(); await openDefaults();
  await expect(dialog.getByLabel('Default Value', { exact: true })).toHaveValue('Not detected');
  await expect(dialog.getByLabel('Placeholder', { exact: true })).toHaveValue('Enter observed result');
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  await page.goto(`/samples/${flow.sample.id}/data_sheets/${flow.job.datasheetId}`);
  const results = page.getByRole('textbox', { name: 'entered_result', exact: true });
  await expect(results).toHaveCount(2);
  for (const result of await results.all()) await expect(result).toHaveValue('000.00');
  await expect(page.getByText('Default value · Enter "-" for blank', { exact: true })).toHaveCount(2);
  const entryCount = async () => (await owner.query('SELECT count(*)::integer AS count FROM job_result_entries WHERE organization_id=$1 AND datasheet_id=$2', [user.organizationId, flow.job.datasheetId])).rows[0].count;
  expect(await entryCount()).toBe(0);
  const valuesPath = `/api/datasheets/${flow.job.datasheetId}/values`; const valuesRoute = `**${valuesPath}`;
  await page.route(valuesRoute, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic default entry interruption' } }) }));
  await results.first().focus(); await page.getByRole('button', { name: 'Calculate', exact: true }).click();
  await expect(page.locator('.tr-details-results-page').getByRole('alert')).toContainText('Synthetic default entry interruption');
  expect(await entryCount()).toBe(0); await expect(results.first()).toHaveValue('000.00');
  await page.unroute(valuesRoute);
  const retried = page.waitForResponse((response) => response.url().endsWith(valuesPath) && response.request().method() === 'PATCH');
  await page.getByRole('button', { name: 'Retry save', exact: true }).click(); expect((await retried).status()).toBe(200);
  await expect(page.getByRole('button', { name: 'Calculate', exact: true })).toBeEnabled();
  await expect(page.locator('.tr-details-results-page').getByRole('alert')).toHaveCount(0);
  expect(await entryCount()).toBe(1);
  await page.reload(); await expect(results.first()).toHaveValue('000.00');
  const fallbackSaved = page.waitForResponse((response) => response.url().endsWith(valuesPath) && response.request().method() === 'PATCH');
  await results.nth(1).fill('   '); await page.getByRole('button', { name: 'Calculate', exact: true }).click();
  expect((await fallbackSaved).status()).toBe(200);
  await expect(page.getByRole('button', { name: 'Calculate', exact: true })).toBeEnabled();
  await expect(results.nth(1)).toHaveValue('000.00'); expect(await entryCount()).toBe(2);
  await page.screenshot({ path: testInfo.outputPath('result-default-capture-desktop.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.lims-main')).toHaveCSS('margin-left', '0px');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('result-default-capture-mobile.png'), fullPage: true, animations: 'disabled' });
  expect(errors).toEqual([]);
});

for (const [resultValueType, secondResult] of [['numeric', '4.20'], ['result', 'Not detected']]) {
  test(`${resultValueType} group results survive failures and retain their parent decision in child activity and the certificate`, async ({ page }, testInfo) => {
    test.setTimeout(60_000);
    const user = await createAccount(owner, { permissions: ['samples.read', 'samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute', 'templates.manage', 'settings.manage'] });
    Object.assign(user, await signIn({ identifier: user.username, password: user.password }));
    const flow = await prepareSubjectJob(owner, user, user, { resultWidget: true, resultValueType });
    const template = await withSession(user.token, createReportTemplate, { csrfToken: user.csrfToken });
    const errors = []; page.on('pageerror', (error) => errors.push(error.message));
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto('/login');
    await page.getByLabel('Username', { exact: true }).fill(user.username);
    await page.getByLabel('Password', { exact: true }).fill(user.password);
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page).toHaveURL(/\/me$/);
    await page.goto(`/samples/${flow.sample.id}/data_sheets/${flow.job.datasheetId}`);
    const raw = page.getByRole('spinbutton', { name: 'raw_0', exact: true });
    const results = page.getByRole('textbox', { name: 'entered_result', exact: true });
    await expect(raw).toHaveCount(2); await expect(results).toHaveCount(2);
    for (let index = 0; index < 2; index += 1) { await raw.nth(index).fill('0'); await results.nth(index).fill(index === 0 ? '0' : secondResult); }
    if (resultValueType === 'result') {
      const valuesRoute = `**/api/datasheets/${flow.job.datasheetId}/values`;
      await page.route(valuesRoute, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic qualitative save interruption' } }) }));
      await results.nth(1).fill('Absent');
      await page.getByRole('button', { name: 'Calculate', exact: true }).click();
      await expect(page.locator('.tr-details-results-page').getByRole('alert')).toContainText('Synthetic qualitative save interruption');
      await expect(results.nth(1)).toHaveValue('Absent');
      await page.unroute(valuesRoute);
      const retrySaved = page.waitForResponse((response) => response.url().endsWith(`/api/datasheets/${flow.job.datasheetId}/values`)
        && response.request().method() === 'PATCH' && response.request().postDataJSON().values.some((value) => value.value === 'Absent'));
      await page.getByRole('button', { name: 'Retry save', exact: true }).click();
      expect((await retrySaved).status()).toBe(200);
      await expect(page.getByRole('button', { name: 'Calculate', exact: true })).toBeEnabled();
      await expect(page.locator('.tr-details-results-page').getByRole('alert')).toHaveCount(0);
      await page.reload(); await expect(results.nth(1)).toHaveValue('Absent');
      await results.nth(1).fill(secondResult);
      await page.getByRole('button', { name: 'Calculate', exact: true }).click();
      await expect(page.getByRole('button', { name: 'Calculate', exact: true })).toBeEnabled();
      await page.screenshot({ path: testInfo.outputPath('qualitative-capture-desktop.png'), fullPage: true, animations: 'disabled' });
      await page.setViewportSize({ width: 390, height: 844 });
      await expect(page.locator('.lims-main')).toHaveCSS('margin-left', '0px');
      await page.screenshot({ path: testInfo.outputPath('qualitative-capture-mobile.png'), fullPage: true, animations: 'disabled' });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await page.setViewportSize({ width: 1440, height: 1000 });
    }
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await expect(page).toHaveURL(`/samples/${flow.sample.id}/test_requests/${flow.job.id}`);
    const transitionRoute = `**/api/workflow-runs/${flow.job.workflowRunId}/datasheet-transitions`;
    await page.route(transitionRoute, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic group decision interruption' } }) }));
    await page.getByRole('button', { name: 'Request Approval', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Request Approval', exact: true });
    await dialog.getByLabel('Comments', { exact: true }).fill('Synthetic group results accepted');
    await dialog.getByRole('button', { name: 'Send Request', exact: true }).click();
    await expect(dialog.getByRole('alert')).toContainText('Synthetic group decision interruption');
    await expect(dialog.getByLabel('Comments', { exact: true })).toHaveValue('Synthetic group results accepted');
    const retained = await page.request.get(`/api/datasheets/${flow.job.datasheetId}`).then((response) => response.json());
    expect(retained.capture.instance.status).toBe('editing'); expect(retained.capture).not.toHaveProperty('pinnedValues');
    await page.unroute(transitionRoute);
    await dialog.getByRole('button', { name: 'Send Request', exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.locator('.tr-details-page-header__title-row')).toContainText('Completed');
    await expect(page.getByRole('link', { name: 'Add Results', exact: true })).toHaveCount(0);
    const completed = await page.request.get(`/api/datasheets/${flow.job.datasheetId}`).then((response) => response.json());
    expect(completed.capture.instance.status).toBe('frozen');
    await page.screenshot({ path: testInfo.outputPath('group-decision-desktop.png'), fullPage: true, animations: 'disabled' });
    for (const child of flow.requests) {
      await page.goto(`/samples/${flow.sample.id}/test_requests/${child.id}`);
      await expect(page.locator('.tr-details-page-header__title-row')).toContainText('Completed');
      await expect(page.getByRole('link', { name: `Job ${flow.job.requestNumber}`, exact: true })).toHaveAttribute('href', `/samples/${flow.sample.id}/test_requests/${flow.job.id}`);
      await expect(page.getByRole('button', { name: 'Request Approval', exact: true })).toHaveCount(0);
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.locator('.lims-main')).toHaveCSS('margin-left', '0px');
    await page.screenshot({ path: testInfo.outputPath('group-child-mobile.png'), fullPage: true, animations: 'disabled' });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto(`/samples/${flow.sample.id}`);
    await page.getByRole('link', { name: 'Test Reports', exact: true }).click();
    await page.getByRole('button', { name: /^Consolidated/ }).click();
    await page.getByLabel('Consolidated Report template', { exact: true }).selectOption(template.templateId);
    await page.getByRole('button', { name: 'Generate', exact: true }).click();
    const report = page.frameLocator('.finalised-report-preview__frame').getByRole('article');
    await expect(report.getByText('CERTIFICATE OF ANALYSIS', { exact: true })).toBeVisible();
    await expect(report.locator('[data-result-test-id]')).toHaveCount(2);
    await expect(report.locator('[data-result-test-id]').nth(0)).toHaveText('0');
    await expect(report.locator('[data-result-test-id]').nth(1)).toHaveText(secondResult);
    await page.reload();
    await expect(report.locator('[data-result-test-id]').nth(0)).toHaveText('0');
    await expect(report.locator('[data-result-test-id]').nth(1)).toHaveText(secondResult);
    await page.screenshot({ path: testInfo.outputPath('group-certificate-desktop.png'), fullPage: true, animations: 'disabled' });
    expect(errors).toEqual([]);
  });
}

test('the source automatic-job setting persists and generated jobs can be allocated through their Jobs card', async ({ page, context }, testInfo) => {
  test.setTimeout(60_000);
  const user = await createAccount(owner, { permissions: ['samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute', 'templates.manage', 'settings.manage'] });
  const source = await createLaboratoryFixture(owner, user, { generateTestRequests: true, repeated: false });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/login');
  await page.getByLabel('Username', { exact: true }).fill(user.username);
  await page.getByLabel('Password', { exact: true }).fill(user.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/me$/);
  await page.goto('/organization_settings');
  await page.getByRole('combobox', { name: 'Job Template', exact: true }).selectOption(source.template.templateId);
  await page.getByRole('tab', { name: 'TR Settings', exact: true }).click();
  const automatic = page.getByRole('checkbox', { name: 'Auto Create Jobs', exact: true });
  await automatic.check();
  const settingsRoute = '**/api/organization-settings/laboratory';
  await page.route(settingsRoute, (route) => route.request().method() === 'PUT'
    ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic automatic setting interruption' } }) }) : route.continue());
  await page.getByRole('button', { name: 'Save Settings', exact: true }).click();
  await expect(page.locator('.settings-layout').getByRole('alert')).toContainText('Synthetic automatic setting interruption');
  await expect(automatic).toBeChecked(); await page.unroute(settingsRoute);
  const saved = page.waitForResponse((response) => response.url().endsWith('/api/organization-settings/laboratory') && response.request().method() === 'PUT');
  await page.getByRole('button', { name: 'Save Settings', exact: true }).click(); expect((await saved).status()).toBe(200);
  await page.reload(); await page.getByRole('tab', { name: 'TR Settings', exact: true }).click(); await expect(automatic).toBeChecked();
  await page.screenshot({ path: testInfo.outputPath('automatic-job-settings.png'), fullPage: true, animations: 'disabled' });
  const cookies = await context.cookies();
  const response = await page.request.post('/api/samples', { headers: { Origin: 'http://127.0.0.1:3100', 'X-CSRF-Token': cookies.find((cookie) => cookie.name === 'sampleify_csrf').value }, data: source.registration });
  expect(response.status()).toBe(201); const sample = await response.json();
  await page.goto(`/samples/${sample.id}/test_requests`);
  const card = page.locator('.smplfy-tr-jobs-card');
  await expect(card).toContainText('1 Jobs'); await expect(card).toContainText('Not allocated');
  await expect(page.locator('.smplfy-tr-requests-card')).toContainText('0 Test Requests');
  const jobLink = card.getByRole('link', { name: /^JOB-/ });
  const number = await jobLink.innerText(); const requestPath = await jobLink.getAttribute('href');
  await card.getByRole('button', { name: 'Allocate', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Allocate Test Request', exact: true });
  await dialog.getByRole('combobox', { name: 'Allocate to', exact: true }).fill('Synthetic Analyst');
  await page.getByRole('option', { name: 'Synthetic Analyst', exact: true }).click();
  await dialog.getByRole('button', { name: 'Allocate', exact: true }).click();
  await expect(dialog).toHaveCount(0); await expect(card.getByRole('button', { name: 'Allocate', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: number, exact: true }).click(); await expect(page).toHaveURL(requestPath);
  await expect(page.getByRole('link', { name: 'Add Results', exact: true })).toBeVisible();
  await page.reload(); await expect(page.getByRole('link', { name: 'Add Results', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
