import { test, expect } from '@playwright/test';
import { ownerPool, createAccount } from '../helpers/database.js';
import { prepareReportFlow } from '../helpers/report-flow.js';
import { createAlternateMethod } from '../helpers/methods.js';
import { signIn } from '../../src/auth/service.js';
import { closePool } from '../../src/db/pool.js';

let owner;
test.beforeAll(() => { owner = ownerPool(); });
test.afterAll(async () => { await closePool(); await owner.end(); });

test('source method dialogs retain failed choices, switch captures, preserve the selected return path and retain deleted history', async ({ page, context }, testInfo) => {
  test.setTimeout(60_000);
  const user = await createAccount(owner, { permissions: ['samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute', 'templates.manage'] });
  const session = await signIn({ identifier: user.username, password: user.password });
  const flow = await prepareReportFlow(owner, { ...user, ...session }, { complete: false });
  const method = await createAlternateMethod(owner, user, flow.fixture);
  const requestPath = `/samples/${flow.sample.id}/test_requests/${flow.requestId}`;
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/login');
  await page.getByLabel('Username', { exact: true }).fill(user.username);
  await page.getByLabel('Password', { exact: true }).fill(user.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/me$/);
  await page.goto(requestPath);
  await page.getByRole('button', { name: 'Add Method', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Add Method', exact: true });
  const selectMethod = async (name) => {
    await dialog.getByRole('combobox', { name: 'Method', exact: true }).selectOption({ label: name });
  };
  await selectMethod(flow.fixture.method.name);
  await dialog.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(dialog).toContainText('This method has already been added.');
  await selectMethod(method.name);
  const routePattern = `**/api/test-requests/${flow.requestId}/methods`;
  await page.route(routePattern, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic method interruption' } }) }));
  await dialog.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(dialog).toContainText('Synthetic method interruption');
  await expect(dialog.getByRole('combobox', { name: 'Method', exact: true })).toHaveValue(method.id);
  await page.screenshot({ path: testInfo.outputPath('method-add-desktop.png'), fullPage: true });
  await page.unroute(routePattern);
  const addedResponse = page.waitForResponse((response) => response.url().endsWith(`/api/test-requests/${flow.requestId}/methods`) && response.request().method() === 'POST');
  await dialog.getByRole('button', { name: 'Add', exact: true }).click();
  const added = await (await addedResponse).json();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator('#tr-method-selector')).toContainText(method.name);
  await page.getByRole('link', { name: 'Add Results', exact: true }).click();
  await expect(page).toHaveURL(`/samples/${flow.sample.id}/data_sheets/${added.datasheetId}`);
  await expect(page.getByRole('spinbutton', { name: 'raw_0', exact: true })).toBeVisible();
  const inputs = page.getByRole('spinbutton');
  for (let index = 0; index < await inputs.count(); index += 1) await inputs.nth(index).fill('0');
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(page).toHaveURL(`${requestPath}?datasheetId=${added.datasheetId}`);
  await expect(page.locator('#tr-method-selector')).toContainText(method.name);
  await page.reload();
  await expect(page.locator('#tr-method-selector')).toContainText(method.name);
  await page.locator('#tr-method-selector').click();
  await page.getByRole('menuitemradio', { name: `Method 1: ${flow.fixture.method.name}`, exact: true }).click();
  await expect(page.getByRole('link', { name: 'Add Results', exact: true })).toHaveAttribute('href', `/samples/${flow.sample.id}/data_sheets/${flow.sheet.id}`);
  await page.locator('#tr-method-selector').click();
  await page.getByRole('menuitemradio', { name: `Method 2: ${method.name}`, exact: true }).click();
  await expect(page.getByRole('link', { name: 'Add Results', exact: true })).toHaveAttribute('href', `/samples/${flow.sample.id}/data_sheets/${added.datasheetId}`);
  const cookies = await context.cookies();
  const headers = { Origin: 'http://127.0.0.1:3100', 'X-CSRF-Token': cookies.find((cookie) => cookie.name === 'sampleify_csrf').value };
  const noCsrf = await page.request.post(`/api/test-requests/${flow.requestId}/methods`, { headers: { Origin: headers.Origin }, data: { revision: added.revision, methodId: method.id } });
  expect(noCsrf.status()).toBe(403);
  await page.getByRole('button', { name: 'Delete method', exact: true }).click();
  const deletion = page.getByRole('dialog', { name: 'Delete method', exact: true });
  await expect(deletion).toContainText('datasheet history will be retained');
  const deletePattern = `**/api/test-requests/${flow.requestId}/methods/${added.datasheetId}`;
  await page.route(deletePattern, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic delete interruption' } }) }));
  await deletion.getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(deletion.getByRole('alert')).toHaveText('Synthetic delete interruption');
  await expect(deletion).toContainText(method.name);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: testInfo.outputPath('method-delete-mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.unroute(deletePattern);
  await deletion.getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(deletion).toHaveCount(0);
  await expect(page.locator('#tr-method-selector')).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Add Results', exact: true })).toHaveAttribute('href', `/samples/${flow.sample.id}/data_sheets/${flow.sheet.id}`);
  const retained = await page.request.get(`/api/datasheets/${added.datasheetId}`).then((response) => response.json());
  expect(retained.datasheet.status).toBe('void'); expect(retained.capture.instance.status).toBe('frozen');
  expect(retained.capture.values.some((value) => value.numberValue === '0')).toBe(true);
  expect(retained.canExecute).toBe(false);
  // A change from another tab must never retarget an open deletion dialog to
  // whichever method becomes selected after the request refreshes.
  await page.getByRole('button', { name: 'Add Method', exact: true }).click();
  await selectMethod(method.name);
  await dialog.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator('#tr-method-selector')).toContainText(method.name);
  const updated = await page.request.get(`/api/test-requests/${flow.requestId}`).then((response) => response.json());
  const latest = updated.datasheets.find((sheet) => sheet.methodId === method.id);
  await page.getByRole('button', { name: 'Delete method', exact: true }).click();
  const external = await page.request.delete(`/api/test-requests/${flow.requestId}/methods/${latest.id}`, { headers, data: { revision: updated.revision } });
  expect(external.status()).toBe(200);
  await deletion.getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(deletion.getByRole('alert')).toContainText('This test request changed.');
  await expect(deletion).toContainText(method.name);
  await expect(deletion.getByRole('button', { name: 'Delete', exact: true })).toBeDisabled();
  await deletion.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect((await page.request.get(`/api/datasheets/${flow.sheet.id}`).then((response) => response.json())).datasheet.status).toBe('in_progress');
  expect(errors).toEqual([]);
});
