import { test, expect } from '@playwright/test';
import { ownerPool, createAccount } from '../helpers/database.js';
import { prepareParameterTitleFlow } from '../helpers/parameter-titles.js';
import { signIn, withSession } from '../../src/auth/service.js';
import { closePool } from '../../src/db/pool.js';
import { createLaboratoryFixture } from '../helpers/laboratory.js';
import { editTemplate } from '../../src/templates/authoring.js';
import { loadDefinition } from '../../src/templates/loader.js';

let owner;
test.beforeAll(() => { owner = ownerPool(); });
test.afterAll(async () => { await closePool(); await owner.end(); });

test('Parameter Detail shows the source control, reconciles a committed lost response, and preserves clone and read-only history', async ({ page }, testInfo) => {
  const user = await createAccount(owner, { permissions: ['masters.manage', 'templates.manage', 'samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute'] });
  const account = { ...user, ...await signIn({ identifier: user.username, password: user.password }) };
  const flow = await prepareParameterTitleFlow(owner, account, { complete: false,
    titles: [['detail_name', 'name'], ['detail_order', 'order'], ['detail_methods', 'moa_applicable'], ['detail_blank', '']].map(([alias, label]) => [alias, label, 'parameter_detail_widget', false]) });
  const api = `/api/datasheets/${flow.sheet.id}`; const path = `/samples/${flow.sample.id}/data_sheets/${flow.sheet.id}`;
  const cells = (alias) => page.locator(`[data-field-id="${flow.datasheetTitles.fields[alias]}"]`);
  const runtime = () => page.request.get(api).then((response) => response.json());
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/login'); await page.getByLabel('Username', { exact: true }).fill(account.username); await page.getByLabel('Password', { exact: true }).fill(account.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page).toHaveURL(/\/me$/);
  await page.goto(path);
  await expect(cells('detail_name')).toHaveText(['Captured parameter', 'Captured parameter']);
  await expect(cells('detail_order')).toHaveText(['0', '0']);
  await expect(cells('detail_methods')).toHaveText([flow.fixture.method.name, flow.fixture.method.name]);
  await expect(page.getByText('Parameter detail refreshed', { exact: true })).toHaveCount(0);
  const initial = await runtime(); let attempted; let committed;
  await page.route(`**${api}/parameter-details`, async (route) => {
    attempted = route.request().postDataJSON();
    const response = await route.fetch(); committed = await response.json();
    expect(response.status()).toBe(200);
    await route.abort('failed');
  });
  await cells('detail_name').first().getByRole('button', { name: 'Refresh detail', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Retry refresh', exact: true })).toBeVisible();
  expect((await runtime()).capture.revision).toBe(initial.capture.revision + 1);
  await expect(cells('detail_name').first().getByRole('button')).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Done', exact: true })).toBeDisabled();
  await page.unroute(`**${api}/parameter-details`);
  const retry = page.waitForResponse((response) => response.url().endsWith(`${api}/parameter-details`));
  await page.getByRole('button', { name: 'Retry refresh', exact: true }).click();
  const retried = await retry; expect(retried.status()).toBe(200); expect(retried.request().postDataJSON()).toEqual(attempted);
  const replay = await retried.json(); expect(replay.replayed).toBe(true); expect(replay.revision).toBe(committed.revision);
  await expect(page.getByText('Parameter detail refreshed', { exact: true })).toBeVisible();
  await expect(cells('detail_name').first().getByRole('button')).toBeEnabled();
  const invalid = page.waitForResponse((response) => response.url().endsWith(`${api}/parameter-details`));
  await cells('detail_blank').first().getByRole('button', { name: 'Refresh detail', exact: true }).click();
  expect((await invalid).status()).toBe(400);
  await expect(page.getByRole('alert').filter({ hasText: 'Please configure detail key' })).toBeVisible();
  expect((await runtime()).capture.revision).toBe(replay.revision);
  const number = page.locator('input[type="number"]').first(); await number.fill('42');
  const refresh = page.waitForResponse((response) => response.url().endsWith(`${api}/parameter-details`));
  await cells('detail_order').first().getByRole('button', { name: 'Refresh detail', exact: true }).click();
  expect((await refresh).status()).toBe(200);
  expect((await runtime()).capture.values.some((value) => value.origin === 'entered' && value.numberValue === '42')).toBe(true);
  const cloned = page.waitForResponse((response) => response.url().endsWith(`${api}/repeats`));
  await cells('detail_name').first().locator('..').getByRole('link', { name: 'Clone row with data', exact: true }).click(); expect((await cloned).status()).toBe(200);
  await expect(cells('detail_name')).toHaveText(['Captured parameter', 'Captured parameter', 'Captured parameter']);
  await page.reload(); await expect(cells('detail_methods')).toHaveText([flow.fixture.method.name, flow.fixture.method.name, flow.fixture.method.name]);
  await cells('detail_name').first().scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath('parameter-detail-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await expect(page.locator('.lims-main')).toHaveCSS('margin-left', '0px');
  await page.screenshot({ path: testInfo.outputPath('parameter-detail-mobile.png'), fullPage: true });
  await page.goto(`${path}?revision=1`);
  await expect(cells('detail_name')).toHaveText(['Captured parameter', 'Captured parameter']);
  for (const button of await page.getByRole('button', { name: 'Refresh detail', exact: true }).all()) await expect(button).toBeDisabled();
  expect(errors).toEqual([]);
});

test('the designer exposes Parameter Detail Title, Key and configured default with its source preview', async ({ page }) => {
  const user = await createAccount(owner, { permissions: ['templates.read', 'templates.manage', 'samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute'] });
  const session = await signIn({ identifier: user.username, password: user.password });
  const fixture = await createLaboratoryFixture(owner, user);
  const added = await withSession(session.token, (client, identity) => editTemplate(client, identity, fixture.template.versionId, 1,
    { type: 'addColumn', rowId: fixture.template.records.rows[0].id }), { csrfToken: session.csrfToken });
  const columnId = added.model.rowsById[fixture.template.records.rows[0].id].columnIds.at(-1);
  await page.goto('/login'); await page.getByLabel('Username', { exact: true }).fill(user.username); await page.getByLabel('Password', { exact: true }).fill(user.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page).toHaveURL(/\/me$/);
  await page.goto(`/master_template_management/${fixture.template.templateId}`);
  await page.getByRole('button', { name: 'Edit Mode Off' }).click();
  const column = page.locator(`[data-col-id="${columnId}"]`);
  await column.locator('.action-dropdown-toggle').click(); await page.getByRole('menuitem', { name: 'Column', exact: true }).click();
  const settings = page.getByRole('dialog', { name: 'Column Settings' });
  await settings.getByRole('combobox', { name: 'Widget' }).fill('Parameter Detail Widget');
  await page.getByRole('option', { name: 'Parameter Detail Widget', exact: true }).click();
  await settings.getByRole('button', { name: 'Save', exact: true }).click(); await expect(settings).toBeHidden();
  await column.locator('.action-dropdown-toggle').click(); await page.getByRole('menuitem', { name: 'Widget', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Widget Configuration' });
  await dialog.getByLabel('Title', { exact: true }).fill('moa_applicable');
  await dialog.getByLabel('Key', { exact: true }).fill('applicable_methods');
  await dialog.getByLabel('Default Value', { exact: true }).fill('Unused configured default');
  await expect(dialog.getByRole('checkbox', { name: 'Editable', exact: true })).toHaveCount(0);
  await expect(dialog.getByText('Use "-" to keep this default as blank / null.', { exact: true })).toBeVisible();
  await dialog.getByRole('button', { name: 'Update data', exact: true }).click(); await expect(dialog).toBeHidden();
  await expect(column).toContainText('Parameter detail preview');
  const { model } = await withSession(session.token, (client, identity) => loadDefinition(client, identity.organization_id, fixture.template.versionId), { readOnly: true });
  const field = model.fieldsById[model.columnsById[columnId].fieldId];
  expect([field.label, field.alias, field.defaultText, field.editable]).toEqual(['moa_applicable', 'applicable_methods', 'Unused configured default', false]);
});
