import { test, expect } from '@playwright/test';
import { ownerPool, createAccount } from '../helpers/database.js';
import { prepareReportFlow } from '../helpers/report-flow.js';
import { signIn, withSession } from '../../src/auth/service.js';
import { closePool } from '../../src/db/pool.js';
import { editTemplate } from '../../src/templates/authoring.js';

let owner;
test.beforeAll(() => { owner = ownerPool(); });
test.afterAll(async () => { await closePool(); await owner.end(); });

test('COA generation retains failed selections, zero margins, repeated final sections and saved report versions', async ({ page }, testInfo) => {
  const user = await createAccount(owner, { permissions: ['samples.read', 'samples.create', 'samples.manage', 'templates.manage', 'test_requests.allocate', 'datasheets.execute'] });
  const account = { ...user, ...await signIn({ identifier: user.username, password: user.password }) };
  const flow = await prepareReportFlow(owner, account, { finalSection: true });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/login');
  await page.getByLabel('Username', { exact: true }).fill(account.username);
  await page.getByLabel('Password', { exact: true }).fill(account.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/me$/);
  await page.goto(`/samples/${flow.sample.id}`);
  await page.getByRole('link', { name: 'Test Reports', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Select Report Type' })).toBeVisible();
  await page.getByRole('button', { name: /^Consolidated/ }).focus(); await page.keyboard.press('Space');
  await page.getByLabel('Consolidated Report template', { exact: true }).selectOption(flow.template.templateId);
  await page.getByRole('button', { name: 'Edit Parameters', exact: true }).click();
  const parameterModal = page.getByRole('dialog', { name: 'Select Parameters' });
  await parameterModal.getByRole('button', { name: 'Clear All', exact: true }).click();
  await expect(parameterModal.getByRole('button', { name: 'Save', exact: true })).toBeDisabled();
  await parameterModal.getByRole('button', { name: 'Select All', exact: true }).click();
  await parameterModal.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByRole('button', { name: 'More actions', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Print Configs', exact: true }).click();
  const config = page.getByRole('dialog', { name: 'Config Sample' });
  await config.getByLabel('X-Axis Margin', { exact: true }).fill('0');
  await config.getByLabel('Print Header', { exact: true }).uncheck();
  await config.getByRole('button', { name: 'Submit', exact: true }).click();
  let firstAttempt;
  const generationPath = `/api/samples/${flow.sample.id}/reports`;
  await page.route(`**${generationPath}`, async (route) => {
    if (route.request().method() !== 'POST') return route.continue();
    firstAttempt = route.request().postDataJSON();
    return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic report generation failure' } }) });
  });
  await page.getByRole('button', { name: 'Generate', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Synthetic report generation failure' })).toBeVisible();
  await expect(page.getByLabel('Consolidated Report template', { exact: true })).toHaveValue(flow.template.templateId);
  await page.unroute(`**${generationPath}`);
  const responsePromise = page.waitForResponse((response) => response.url().endsWith(generationPath) && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Generate', exact: true }).click();
  const response = await responsePromise; expect(response.status()).toBe(201);
  expect(response.request().postDataJSON().requestId).toBe(firstAttempt.requestId);
  const generated = await response.json(); const reportId = generated.items[0].id;
  const report = page.getByRole('article', { name: generated.items[0].reportNumber });
  await expect(report.getByText('CERTIFICATE OF ANALYSIS', { exact: true })).toBeVisible();
  await expect(report.locator('[data-result-test-id] [data-field-id]')).toHaveCount(6);
  await expect(report.locator('[data-result-test-id] [data-field-id]').first()).toContainText('0.00');
  expect(await report.locator('[data-is-param-loop]').count()).toBe(1);
  const saved = await page.request.get(`/api/reports/${reportId}`).then((result) => result.json());
  expect(saved.printConfig.xMargin).toBe('0'); expect(saved.printConfig.printHeader).toBe(false);
  expect(saved.metrics.definition.queryCount).toBe(8); expect(saved.metrics.capture.queryCount).toBe(3);
  await page.screenshot({ path: testInfo.outputPath('coa-report-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.locator('.lims-main').evaluate((element) => Math.round(element.getBoundingClientRect().left))).toBe(0);
  await expect(report).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  expect(await page.locator('.finalised-report-page-header').evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('coa-report-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });

  const title = flow.template.records.fields[0];
  await withSession(account.token, (client, identity) => editTemplate(client, identity, flow.template.versionId, 1,
    { type: 'configureField', columnId: title.columnId, widget: 'text_widget', label: 'New report title' }), { csrfToken: account.csrfToken });
  await page.getByRole('button', { name: 'More actions', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Regenerate', exact: true }).click();
  await page.getByRole('button', { name: 'Generate', exact: true }).click();
  await expect(page.getByRole('article').getByText('New report title', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Version 2', exact: true }).click();
  await page.getByRole('menuitemradio', { name: 'Version 1', exact: true }).click();
  await expect(page.getByRole('article').getByText('CERTIFICATE OF ANALYSIS', { exact: true })).toBeVisible();
  await expect(page.getByRole('article').getByText('New report title', { exact: true })).toHaveCount(0);
  const unauthenticatedWrite = await page.request.post(generationPath, { data: firstAttempt, headers: { Origin: 'http://127.0.0.1:3100' } });
  expect(unauthenticatedWrite.status()).toBe(403);
  expect(errors).toEqual([]);
});
