import { test, expect } from '@playwright/test';
import sharp from 'sharp';
import { ownerPool, createAccount } from '../helpers/database.js';
import { closePool } from '../../src/db/pool.js';
import { signIn, withSession } from '../../src/auth/service.js';
import { prepareReportFlow } from '../helpers/report-flow.js';
import { createReportAssets } from '../helpers/report-assets.js';
import { saveReportDocument } from '../../src/report-assets/documents.js';
import { randomUUID } from 'node:crypto';
import { reportSvg } from '../helpers/report-svg.js';

let owner;
test.beforeAll(() => { owner = ownerPool(); });
test.afterAll(async () => { await closePool(); await owner.end(); });
async function login(page, account) {
  await page.goto('/login');
  await page.getByLabel('Username', { exact: true }).fill(account.username);
  await page.getByLabel('Password', { exact: true }).fill(account.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/me$/);
}

test('source rich header editor uploads an image, survives a lost save response, reloads and retains deleted history', async ({ page }, testInfo) => {
  test.setTimeout(60_000);
  const account = await createAccount(owner, { permissions: ['report_settings.read', 'report_settings.manage'] });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await login(page, account); await page.goto('/header_management');
  await expect(page.getByText('No header templates found.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'New Header', exact: true }).click();
  const modal = page.getByRole('dialog', { name: 'New Header Template' });
  await modal.getByLabel('Name', { exact: true }).fill('Synthetic laboratory header');
  await modal.getByLabel('Default header', { exact: false }).check();
  const editor = modal.locator('.ck-editor__editable');
  await expect(editor).toBeVisible();
  await editor.fill('SYNTHETIC LABORATORY');
  await page.keyboard.press('End'); await page.keyboard.press('Enter');
  const logo = await sharp({ create: { width: 160, height: 40, channels: 3, background: '#005577' } }).png().toBuffer();
  const uploadResponse = page.waitForResponse((response) => response.url().endsWith('/api/report-assets/images') && response.request().method() === 'POST');
  await modal.locator('input[type=file]').setInputFiles({ name: 'Lab logo.png', mimeType: 'image/png', buffer: logo });
  const imageResponse = await uploadResponse; expect(imageResponse.status()).toBe(201);
  const image = await imageResponse.json();
  await expect(editor.locator(`img[src="${image.url}"]`)).toBeVisible();
  await expect(modal.getByRole('button', { name: 'Save Template', exact: true })).toBeEnabled();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: testInfo.outputPath('header-source-editor-desktop.png'), fullPage: true, animations: 'disabled' });
  let requestId;
  await page.route('**/api/report-assets/documents', async (route) => {
    if (route.request().method() !== 'POST') return route.continue();
    requestId = route.request().postDataJSON().requestId;
    const saved = await route.fetch(); expect(saved.status()).toBe(201);
    await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic lost template response' } }) });
  });
  await modal.getByRole('button', { name: 'Save Template', exact: true }).click();
  await expect(modal.getByRole('alert')).toContainText('Synthetic lost template response');
  await expect(editor).toContainText('SYNTHETIC LABORATORY');
  await page.unroute('**/api/report-assets/documents');
  const retryResponse = page.waitForResponse((response) => response.url().endsWith('/api/report-assets/documents') && response.request().method() === 'POST');
  await modal.getByRole('button', { name: 'Save Template', exact: true }).click();
  const retry = await retryResponse; expect(retry.status()).toBe(200); expect(retry.request().postDataJSON().requestId).toBe(requestId);
  const saved = await retry.json(); expect(saved.replayed).toBe(true);
  await expect(modal).not.toBeVisible();
  await expect(page.locator('.hf-template-name')).toHaveText('Synthetic laboratory header');
  await expect(page.locator('.hf-template-preview img')).toBeVisible();
  await page.reload();
  await expect(page.locator('.hf-template-default-summary')).toContainText('Synthetic laboratory header');
  const fetched = await page.request.get(image.url); expect(fetched.status()).toBe(200); expect(await fetched.body()).toEqual(logo);
  expect(fetched.headers()['x-content-type-options']).toBe('nosniff');
  const deniedCsrf = await page.request.post('/api/report-assets/images', { headers: { 'Content-Type': 'image/png', Origin: 'http://127.0.0.1:3100' }, data: logo });
  expect(deniedCsrf.status()).toBe(403);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.locator('.lims-main').evaluate((element) => Math.round(element.getBoundingClientRect().left))).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('header-source-list-mobile.png'), fullPage: true, animations: 'disabled' });
  page.once('dialog', (dialog) => dialog.accept());
  await page.getByRole('button', { name: 'Delete Synthetic laboratory header', exact: true }).click();
  await expect(page.getByText('No header templates found.', { exact: true })).toBeVisible();
  const versions = (await owner.query('SELECT revision,is_retired FROM report_document_versions WHERE organization_id=$1 AND document_id=$2 ORDER BY revision', [account.organizationId, saved.document.id])).rows;
  expect(versions).toEqual([{ revision: 1, is_retired: false }, { revision: 2, is_retired: true }]);
  expect(errors).toEqual([]);
});

test('the source rich editor captures a static SVG and rejects executable vector uploads', async ({ page }, testInfo) => {
  const account = await createAccount(owner, { permissions: ['report_settings.manage'] });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await login(page, account); await page.goto('/header_management');
  await page.getByRole('button', { name: 'New Header', exact: true }).click();
  const modal = page.getByRole('dialog', { name: 'New Header Template' });
  await modal.getByLabel('Name', { exact: true }).fill('Vector header');
  await expect(modal.locator('.ck-editor__editable')).toBeVisible();
  const uploaded = page.waitForResponse((response) => response.url().endsWith('/api/report-assets/images') && response.request().method() === 'POST');
  await modal.locator('input[type=file]').setInputFiles({ name: 'Vector.svg', mimeType: 'image/svg+xml', buffer: reportSvg });
  const response = await uploaded; expect(response.status()).toBe(201); const vector = await response.json();
  await expect(modal.locator(`.ck-editor__editable img[src="${vector.url}"]`)).toBeVisible();
  await expect(modal.getByRole('button', { name: 'Save Template', exact: true })).toBeEnabled();
  await modal.getByRole('button', { name: 'Save Template', exact: true }).click();
  await expect(modal).not.toBeVisible();
  const image = page.locator('.hf-template-preview img');
  await expect(image).toBeVisible(); await image.evaluate((element) => element.decode());
  const downloaded = await page.request.get(vector.url); expect(await downloaded.body()).toEqual(reportSvg);
  expect(downloaded.headers()['content-type']).toContain('image/svg+xml');
  expect(downloaded.headers()['content-security-policy']).toBe("default-src 'none'; style-src 'unsafe-inline'; sandbox");
  const csrf = (await page.context().cookies()).find((cookie) => cookie.name === 'sampleify_csrf').value;
  const unsafe = await page.request.post('/api/report-assets/images', { headers: { Origin: 'http://127.0.0.1:3100', 'X-CSRF-Token': csrf,
    'Content-Type': 'image/svg+xml', 'X-Upload-Request-Id': randomUUID(), 'X-File-Name': 'Unsafe.svg' },
  data: '<svg xmlns="http://www.w3.org/2000/svg" onload="alert(1)"/>' });
  expect(unsafe.status()).toBe(422); expect((await unsafe.json()).error.code).toBe('unsafe_report_svg');
  await page.screenshot({ path: testInfo.outputPath('captured-vector-header.png'), fullPage: true, animations: 'disabled' });
  expect(errors).toEqual([]);
});

test('read-only report settings hide mutations and enforce direct endpoint permissions', async ({ page }) => {
  const account = await createAccount(owner, { permissions: ['report_settings.read'] });
  await login(page, account); await page.goto('/footer_management');
  await expect(page.getByText('No footer templates found.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'New Footer', exact: true })).toHaveCount(0);
  const csrf = (await page.context().cookies()).find((cookie) => cookie.name === 'sampleify_csrf').value;
  const response = await page.request.post('/api/report-assets/documents', { headers: { Origin: 'http://127.0.0.1:3100', 'X-CSRF-Token': csrf }, data: {} });
  expect(response.status()).toBe(403);
});

test('source template settings bind headers and footers to a COA that retains its saved branding', async ({ page }, testInfo) => {
  test.setTimeout(60_000);
  const user = await createAccount(owner, { permissions: ['templates.read', 'templates.manage', 'samples.read', 'samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute', 'report_settings.manage'] });
  const session = await signIn({ identifier: user.username, password: user.password }); const account = { ...user, ...session };
  const work = (callback) => withSession(session.token, callback, { csrfToken: session.csrfToken });
  const flow = await prepareReportFlow(owner, account); const assets = await work(createReportAssets);
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await login(page, account); await page.goto(`/master_template_management/${flow.template.templateId}`);
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  const settings = page.getByRole('dialog', { name: 'Settings', exact: true });
  await expect(settings.getByRole('combobox', { name: 'Non NABL Header', exact: true })).toBeEnabled();
  await expect(settings.getByRole('combobox', { name: 'Non NABL Header', exact: true })).toHaveValue('');
  await settings.getByRole('combobox', { name: 'Non NABL Header', exact: true }).selectOption(assets.header.id);
  await settings.getByRole('combobox', { name: 'Non-NABL Footer', exact: true }).selectOption(assets.footer.id);
  await expect(settings.getByRole('combobox', { name: 'NABL Header', exact: true })).toHaveValue('');
  await page.screenshot({ path: testInfo.outputPath('template-source-asset-settings.png'), fullPage: true, animations: 'disabled' });
  await settings.getByRole('button', { name: 'Save Settings', exact: true }).click();
  await expect(settings).not.toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await expect(settings.getByRole('combobox', { name: 'Non NABL Header', exact: true })).toHaveValue(assets.header.id);
  await settings.getByRole('button', { name: 'Close', exact: true }).click();
  await page.goto(`/samples/${flow.sample.id}/coa`);
  await page.getByRole('button', { name: /^Consolidated/ }).click();
  await page.getByLabel('Consolidated Report template', { exact: true }).selectOption(flow.template.templateId);
  await page.getByRole('button', { name: 'Generate', exact: true }).click();
  const report = page.getByRole('article');
  await expect(report.getByText('FROZEN LABORATORY HEADER', { exact: true })).toBeVisible();
  await expect(report.getByText('FROZEN LABORATORY FOOTER', { exact: true })).toBeVisible();
  await expect(report.locator('img[alt="Synthetic logo"]')).toBeVisible();
  await work((client, identity) => saveReportDocument(client, identity, { ...assets.headerInput, revision: 1, requestId: randomUUID(), templateHtml: '<p>CHANGED LATER</p>' }));
  await page.reload();
  await expect(report.getByText('FROZEN LABORATORY HEADER', { exact: true })).toBeVisible();
  await expect(report.getByText('CHANGED LATER', { exact: true })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath('coa-captured-assets-desktop.png'), fullPage: true, animations: 'disabled' });
  expect(errors).toEqual([]);
});
