import { test, expect } from '@playwright/test';
import { ownerPool, createAccount } from '../helpers/database.js';
import { createLaboratoryFixture } from '../helpers/laboratory.js';
import { signIn, withSession } from '../../src/auth/service.js';
import { closePool } from '../../src/db/pool.js';
import { editTemplate } from '../../src/templates/authoring.js';
import { registerSample } from '../../src/samples/register.js';
import { generateTestRequests } from '../../src/test-requests/generate.js';
import { allocateTestRequest } from '../../src/test-requests/allocate.js';

let owner;
test.beforeAll(() => { owner = ownerPool(); });
test.afterAll(async () => { await closePool(); await owner.end(); });

test('vertical Text and derived Text defaults retain source controls, literal rendering, repeats and frozen titles', async ({ page, context }, testInfo) => {
  test.setTimeout(90_000);
  const account = await createAccount(owner, { permissions: ['templates.read', 'templates.manage', 'samples.read', 'samples.create', 'samples.manage', 'test_requests.allocate', 'datasheets.execute'] });
  const fixture = await createLaboratoryFixture(owner, account);
  const session = await signIn({ identifier: account.username, password: account.password });
  const work = (action) => withSession(session.token, action, { csrfToken: session.csrfToken });
  let revision = 1;
  const addColumn = async () => {
    const result = await work((client, identity) => editTemplate(client, identity, fixture.template.versionId, revision, { type: 'addColumn', rowId: fixture.template.records.rows[0].id }));
    revision = result.model.version.revision;
    return result.model.rowsById[fixture.template.records.rows[0].id].columnIds.at(-1);
  };
  const verticalColumn = await addColumn(); const textColumn = await addColumn();
  await work((client, identity) => editTemplate(client, identity, fixture.template.versionId, revision,
    { type: 'configureField', columnId: textColumn, widget: 'text_widget', alias: 'text_title', label: 'Original title' }));
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/login'); await page.getByLabel('Username', { exact: true }).fill(account.username); await page.getByLabel('Password', { exact: true }).fill(account.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page).toHaveURL(/\/me$/);
  await page.goto(`/master_template_management/${fixture.template.templateId}`);
  const vertical = page.locator(`[data-col-id="${verticalColumn}"]`);
  const dock = page.getByRole('complementary', { name: 'Properties' });
  const dialog = page.getByRole('dialog', { name: 'Configure field' });
  const settings = page.getByRole('dialog', { name: 'Column Settings' });
  const save = (host, name) => {
    const response = page.waitForResponse((r) => r.url().endsWith(`/api/template-versions/${fixture.template.versionId}`) && r.request().method() === 'PATCH');
    return async () => { await host.getByRole('button', { name, exact: true }).click(); expect((await response).status()).toBe(200); };
  };
  await vertical.locator('.template-studio-field-action').click();
  await settings.getByRole('combobox', { name: 'Widget' }).fill('Vertical Text Widget');
  await page.getByRole('option', { name: 'Vertical Text Widget', exact: true }).click();
  await save(settings, 'Save')();
  const configure = async (column) => {
    await column.locator('.template-studio-field-action').click();
    await expect(dialog).toBeVisible();
  };
  await configure(vertical);
  await dialog.getByLabel('Title', { exact: true }).fill('0'); await dialog.getByLabel('Key', { exact: true }).fill('vertical_title');
  await dialog.getByLabel('Default Value', { exact: true }).fill('Unused default');
  await expect(dialog.getByLabel('Default Value', { exact: true })).toBeEnabled();
  await expect(dialog.getByRole('checkbox', { name: 'Editable', exact: true })).toHaveCount(0);
  await save(dialog, 'Save field')();
  const paragraph = vertical.locator('.row1 p');
  await expect(paragraph).toHaveText('0'); await expect(paragraph).toHaveCSS('writing-mode', 'vertical-rl');
  await expect(paragraph).toHaveCSS('transform', 'matrix(-1, 0, 0, -1, 0, 0)');
  await configure(page.locator(`[data-col-id="${textColumn}"]`));
  const defaultInput = dialog.getByLabel('Default Value', { exact: true });
  await expect(defaultInput).toBeDisabled(); await expect(defaultInput).toHaveValue('Original title');
  await dialog.getByLabel('Title', { exact: true }).fill('0'); await expect(defaultInput).toHaveValue('0');
  await dialog.getByLabel('Title', { exact: true }).fill(''); await expect(defaultInput).toHaveValue('');
  await dialog.getByLabel('Title', { exact: true }).fill('Frozen title'); await expect(defaultInput).toHaveValue('Frozen title');
  await save(dialog, 'Save field')();
  await configure(vertical);
  await expect(dialog.getByLabel('Default Value', { exact: true })).toHaveValue('Unused default');
  const title = 'Literal <b>title</b>';
  await dialog.getByLabel('Title', { exact: true }).fill(title);
  await save(dialog, 'Save field')();
  await expect(paragraph).toHaveText(title); await expect(paragraph.locator('b')).toHaveCount(0);
  const previewPromise = context.waitForEvent('page'); await page.getByRole('link', { name: 'Print Preview', exact: true }).click();
  const preview = await previewPromise;
  const previewTitle = preview.locator(`[data-col-id="${verticalColumn}"] .row1 p`);
  await expect(previewTitle).toHaveText(title); await expect(previewTitle).toHaveCSS('writing-mode', 'vertical-rl');
  await preview.emulateMedia({ media: 'print' }); await expect(previewTitle).toHaveCSS('transform', 'matrix(-1, 0, 0, -1, 0, 0)');
  await preview.close();
  const sample = await work((client, identity) => registerSample(client, identity, fixture.registration));
  const generated = await work((client, identity) => generateTestRequests(client, identity, sample.id));
  const allocated = await work((client, identity) => allocateTestRequest(client, identity, generated.items[0].id, { revision: 1, assignmentType: 'analyst', assignedUserId: account.userId }));
  const path = `/samples/${sample.id}/data_sheets/${allocated.datasheetId}`;
  await page.goto(path);
  await expect(paragraph).toHaveText([title, title]);
  await expect(vertical.locator('input')).toHaveCount(0);
  const runtime = await page.request.get(`/api/datasheets/${allocated.datasheetId}`).then((response) => response.json());
  const fieldId = runtime.model.columnsById[verticalColumn].fieldId;
  expect(runtime.capture.values.some((value) => value.fieldId === fieldId)).toBe(false);
  const draft = await page.request.get(`/api/templates/${fixture.template.templateId}`).then((response) => response.json());
  expect(draft.model.version.status).toBe('draft');
  await work((client, identity) => editTemplate(client, identity, draft.model.version.id, draft.model.version.revision,
    { type: 'configureField', columnId: verticalColumn, widget: 'vertical_text_widget', alias: 'vertical_title', label: 'Later title' }));
  await page.reload(); await expect(paragraph).toHaveText([title, title]);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('vertical-text-mobile.png'), fullPage: true, animations: 'disabled' });
  expect(errors).toEqual([]);
});
