import { HttpError } from '../auth/errors.js';
import { dateOnly, fieldsOnly, integer, requirePermission, text, uuid } from '../templates/input.js';
import { customFieldInput } from './custom-field-input.js';
import { customFieldCaptureLimit, customFieldTypes } from './custom-field-config.js';

const columns = {
  key: 'key', label: 'label', description: 'description', autoGenerated: 'auto_generated', scheme: 'scheme',
  nablDisplayTerm: 'nabl_display_term', nonNablDisplayTerm: 'non_nabl_display_term', fieldType: 'field_type', associatedWith: 'associated_with',
  showInList: 'show_in_list', showInFilter: 'show_in_filter', allowsMultiple: 'allows_multiple', isRequired: 'is_required',
  paddedNumber: 'padded_number', displayOrder: 'display_order', dateFormat: 'date_format', datetimeFormat: 'datetime_format', generatedAt: 'generated_at',
  associateRoleSpecificUsers: 'associate_role_specific_users', associatedWithRoleId: 'associated_with_role_id', splitter: 'splitter',
  filterSearchType: 'filter_search_type', showInDashboard: 'show_in_dashboard', showInReport: 'show_in_report',
  validateUniqueness: 'validate_uniqueness', hideFromSampleCreation: 'hide_from_sample_creation',
};
const authoredFields = (record) => ({ ...Object.fromEntries(Object.keys(columns).map((key) => [key, record[key]])),
  options: record.options, roleIdsCanEdit: record.roleIdsCanEdit });
function requireRead(identity) {
  if (!identity.permission_codes?.some((permission) => ['masters.read', 'masters.manage'].includes(permission))) throw new HttpError(403, 'forbidden', 'You cannot view custom fields.');
}

async function masterCustomFields(association, client, identity, { forListing = false } = {}) {
  requireRead(identity);
  const fields = (await client.query(`SELECT definition.id,definition.revision,field.field_id AS "versionId",
    field.option_count AS "optionCount",${Object.entries(columns).map(([key, column]) => `field.${column} AS "${key}"`).join(',')}
    FROM (SELECT id,revision,organization_id FROM custom_field_definitions
      WHERE organization_id=$1 AND associated_with=$3 AND active ${forListing ? 'AND (show_in_list OR show_in_filter)' : ''}
      ORDER BY display_order,label,id LIMIT $2) definition
    LEFT JOIN custom_field_versions field ON field.organization_id=definition.organization_id
      AND field.field_id=definition.id AND field.revision=definition.revision`,
  [identity.organization_id, customFieldCaptureLimit + 1, association])).rows;
  if (fields.length > customFieldCaptureLimit) throw new HttpError(409, 'custom_field_limit', `This form supports at most ${customFieldCaptureLimit} Custom Fields.`);
  const incomplete = () => new HttpError(409, 'incomplete_custom_field', 'A Custom Field definition is incomplete. Reload before continuing.');
  if (fields.some((field) => field.versionId !== field.id)) throw incomplete();
  const selectable = fields.filter((field) => field.fieldType === 'select' && field.optionCount > 0);
  const byVersion = new Map(fields.map((field) => [`${field.id}:${field.revision}`, { ...field, options: [] }]));
  if (selectable.length) {
    const options = (await client.query(`SELECT option.field_id AS "fieldId",option.revision,option.id,option.key,option.label,option.position
      FROM unnest($2::uuid[],$3::integer[]) AS requested(field_id,revision)
      JOIN custom_field_version_options option ON option.organization_id=$1
        AND option.field_id=requested.field_id AND option.revision=requested.revision
      ORDER BY option.field_id,option.revision,option.position`,
    [identity.organization_id, selectable.map((field) => field.id), selectable.map((field) => field.revision)])).rows;
    for (const option of options) {
      const field = byVersion.get(`${option.fieldId}:${option.revision}`);
      if (!field || option.position !== field.options.length) throw incomplete();
      field.options.push({ id: option.id, key: option.key, label: option.label });
    }
  }
  // GenericForm ignores edit-role settings here and uses options only for select controls.
  const result = [...byVersion.values()].map(({ versionId: _versionId, optionCount, ...field }) => {
    if (field.fieldType === 'select' && field.options.length !== optionCount) throw incomplete();
    return field;
  });
  const compareText = (left, right) => left < right ? -1 : left > right ? 1 : 0;
  return result.sort((left, right) => left.displayOrder - right.displayOrder || compareText(left.label, right.label) || compareText(left.id, right.id));
}

export const productCustomFields = (...args) => masterCustomFields('product', ...args);
export const parameterCustomFields = (...args) => masterCustomFields('parameter', ...args);

export async function loadCustomField(client, identity, fieldId, { atRevision } = {}) {
  requireRead(identity); uuid(fieldId, 'Custom field');
  if (atRevision !== undefined) integer(atRevision, 'Revision', 1, 2_147_483_647);
  const history = atRevision !== undefined;
  const record = (await client.query(`SELECT field.field_id AS id,field.revision,field.active,
    ${Object.entries(columns).map(([key, column]) => `field.${column} AS "${key}"`).join(',')},
    field.saved_by AS "savedBy",field.saved_at AS "savedAt",field.saved_at AS "updatedAt",field.previous_revision AS "previousRevision",
    field.operation,definition.created_at AS "createdAt",associated_role.name AS "associatedWithRoleName"
    FROM custom_field_definitions definition JOIN custom_field_versions field ON field.organization_id=definition.organization_id
      AND field.field_id=definition.id AND field.revision=${history ? '$3' : 'definition.revision'}
    LEFT JOIN roles associated_role ON associated_role.organization_id=field.organization_id AND associated_role.id=field.associated_with_role_id
    WHERE definition.organization_id=$1 AND definition.id=$2 ${history ? '' : 'AND definition.active'}`,
  history ? [identity.organization_id, fieldId, atRevision] : [identity.organization_id, fieldId])).rows[0];
  if (!record) throw new HttpError(404, 'custom_field_not_found', 'Custom field was not found.');
  const options = (await client.query(`SELECT id,key,label FROM custom_field_version_options
    WHERE organization_id=$1 AND field_id=$2 AND revision=$3 ORDER BY position`, [identity.organization_id, fieldId, record.revision])).rows;
  const editRoles = (await client.query(`SELECT link.role_id AS id,role.name FROM custom_field_version_edit_roles link
    JOIN roles role ON role.organization_id=link.organization_id AND role.id=link.role_id
    WHERE link.organization_id=$1 AND link.field_id=$2 AND link.revision=$3 ORDER BY link.position`, [identity.organization_id, fieldId, record.revision])).rows;
  return { ...record, options, editRoles, roleIdsCanEdit: editRoles.map((role) => role.id) };
}

async function priorSave(client, identity, id, revision, requestId, operation) {
  await client.query("SELECT pg_advisory_xact_lock(hashtextextended('custom-field-save:'||$1::text||':'||$2::text,0))", [identity.organization_id, requestId]);
  const prior = (await client.query(`SELECT field_id,revision,previous_revision,operation,saved_by
    FROM custom_field_versions WHERE organization_id=$1 AND request_id=$2`, [identity.organization_id, requestId])).rows[0];
  if (!prior) return null;
  if (prior.field_id !== id || (prior.previous_revision ?? 0) !== revision || prior.operation !== operation || prior.saved_by !== identity.user_id) {
    throw new HttpError(409, 'save_request_reused', 'This save request was already used for another change.');
  }
  return loadCustomField(client, identity, id, { atRevision: prior.revision });
}

async function appendLinks(client, organizationId, input) {
  if (input.options.length) await client.query(`INSERT INTO custom_field_version_options(organization_id,field_id,revision,id,key,label,position)
    SELECT $1,$2,$3,id,key,label,position-1 FROM unnest($4::uuid[],$5::text[],$6::text[]) WITH ORDINALITY AS options(id,key,label,position)`,
  [organizationId, input.id, input.revision + 1, input.options.map((option) => option.id), input.options.map((option) => option.key), input.options.map((option) => option.label)]);
  if (input.roleIdsCanEdit.length) await client.query(`INSERT INTO custom_field_version_edit_roles(organization_id,field_id,revision,role_id,position)
    SELECT $1,$2,$3,role_id,position-1 FROM unnest($4::uuid[]) WITH ORDINALITY AS roles(role_id,position)`,
  [organizationId, input.id, input.revision + 1, input.roleIdsCanEdit]);
}

export async function saveCustomField(client, identity, value) {
  requirePermission(identity, 'masters.manage'); const input = customFieldInput(value);
  await client.query("SELECT pg_advisory_xact_lock(hashtextextended('custom-field-definitions:'||$1::text,0))", [identity.organization_id]);
  const prior = await priorSave(client, identity, input.id, input.revision, input.requestId, input.revision ? 'update' : 'create');
  if (prior) {
    if (JSON.stringify(authoredFields(prior)) !== JSON.stringify(authoredFields(input))) throw new HttpError(409, 'save_request_reused', 'This save request was already used for different values.');
    return prior;
  }
  const current = (await client.query('SELECT revision,active FROM custom_field_definitions WHERE organization_id=$1 AND id=$2 FOR UPDATE', [identity.organization_id, input.id])).rows[0];
  if (input.revision && !current?.active) throw new HttpError(404, 'custom_field_not_found', 'Custom field was not found.');
  if ((current?.revision ?? 0) !== input.revision) throw new HttpError(409, 'stale_custom_field', 'The custom field changed. Reload before saving.');
  const roles = [...new Set([...input.roleIdsCanEdit, input.associatedWithRoleId].filter(Boolean))];
  // The composite FKs protect concurrent deletion; role validation needs only SELECT permission.
  if (roles.length && (await client.query('SELECT id FROM roles WHERE organization_id=$1 AND id=ANY($2::uuid[]) ORDER BY id', [identity.organization_id, roles])).rowCount !== roles.length) {
    throw new HttpError(400, 'invalid_custom_field_roles', 'Select roles in this organization.');
  }
  const names = [...Object.values(columns), 'option_count', 'edit_role_count', 'save_request_id'];
  const args = [identity.organization_id, input.id, ...Object.keys(columns).map((key) => input[key]), input.options.length, input.roleIdsCanEdit.length, input.requestId];
  try {
    if (!input.revision) await client.query(`INSERT INTO custom_field_definitions(organization_id,id,${names.join(',')}) VALUES(${args.map((_, index) => `$${index + 1}`).join(',')})`, args);
    else await client.query(`UPDATE custom_field_definitions SET ${names.map((name, index) => `${name}=$${index + 3}`).join(',')},revision=revision+1,updated_at=transaction_timestamp()
      WHERE organization_id=$1 AND id=$2`, args);
    await appendLinks(client, identity.organization_id, input);
  } catch (error) {
    if (error.constraint === 'custom_field_save_request_key') throw new HttpError(409, 'save_request_reused', 'This save request was already used for another change.');
    if (error.constraint === 'custom_field_active_key') throw new HttpError(409, 'duplicate_custom_field_key', 'This custom field key is already in use.');
    if (error.constraint === 'custom_field_pk') throw new HttpError(409, 'custom_field_exists', 'This custom field identifier is already in use.');
    if (['custom_field_associated_role_fk', 'custom_field_version_associated_role_fk', 'custom_field_edit_role_fk'].includes(error.constraint)) {
      throw new HttpError(400, 'invalid_custom_field_roles', 'Select roles in this organization.');
    }
    throw error;
  }
  return loadCustomField(client, identity, input.id);
}

export async function retireCustomField(client, identity, input) {
  requirePermission(identity, 'masters.manage'); fieldsOnly(input, ['id', 'revision', 'requestId']);
  const id = uuid(input.id, 'Custom field').toLowerCase(); const requestId = uuid(input.requestId, 'Delete request').toLowerCase();
  const revision = integer(input.revision, 'Revision', 1, 2_147_483_646);
  await client.query("SELECT pg_advisory_xact_lock(hashtextextended('custom-field-definitions:'||$1::text,0))", [identity.organization_id]);
  const prior = await priorSave(client, identity, id, revision, requestId, 'retire');
  if (prior) return { id, revision: prior.revision };
  const current = (await client.query('SELECT revision,active FROM custom_field_definitions WHERE organization_id=$1 AND id=$2 FOR UPDATE', [identity.organization_id, id])).rows[0];
  if (!current?.active) throw new HttpError(404, 'custom_field_not_found', 'Custom field was not found.');
  if (current.revision !== revision) throw new HttpError(409, 'stale_custom_field', 'The custom field changed. Reload before deleting.');
  await client.query(`UPDATE custom_field_definitions SET active=false,revision=revision+1,save_request_id=$3,updated_at=transaction_timestamp()
    WHERE organization_id=$1 AND id=$2`, [identity.organization_id, id, requestId]);
  await client.query(`INSERT INTO custom_field_version_options(organization_id,field_id,revision,id,key,label,position)
    SELECT organization_id,field_id,revision+1,id,key,label,position FROM custom_field_version_options
    WHERE organization_id=$1 AND field_id=$2 AND revision=$3`, [identity.organization_id, id, revision]);
  await client.query(`INSERT INTO custom_field_version_edit_roles(organization_id,field_id,revision,role_id,position)
    SELECT organization_id,field_id,revision+1,role_id,position FROM custom_field_version_edit_roles
    WHERE organization_id=$1 AND field_id=$2 AND revision=$3`, [identity.organization_id, id, revision]);
  return { id, revision: revision + 1 };
}

const literalSearch = (value) => `%${value.replace(/[\\%_]/g, '\\$&')}%`;
function searchText(value, label) {
  const result = text(value, label, 500, { optional: true }).trim();
  if (result.includes('\0')) throw new HttpError(400, 'invalid_input', `${label} cannot contain null characters.`);
  return result;
}
const listColumns = { label: 'field.label', description: 'field.description', key: 'field.key', associated_with: 'field.associated_with',
  scheme: 'field.scheme', data_type: 'field.field_type', created_at: 'field.created_at' };

export function customFieldDateRange(filter) {
  const from = filter.from == null || filter.from === '' ? null : dateOnly(filter.from);
  const to = filter.to == null || filter.to === '' ? null : dateOnly(filter.to);
  if (from && to && from > to) throw new HttpError(400, 'invalid_filter', 'The start date must be before the end date.');
  // Match the source server's Date parsing and local-day boundaries. An exclusive end also covers PostgreSQL microseconds.
  const start = from ? new Date(from) : null; const before = to ? new Date(to) : null;
  start?.setHours(0, 0, 0, 0);
  if (before) { before.setHours(0, 0, 0, 0); before.setDate(before.getDate() + 1); }
  return { start, before };
}

export async function listCustomFields(client, identity, input = {}) {
  requireRead(identity); fieldsOnly(input, ['page', 'pageSize', 'search', 'filters', 'sort']);
  const page = integer(input.page ?? 1, 'Page', 1, 1_000_000); const pageSize = integer(input.pageSize ?? 10, 'Page size', 1, 100);
  const search = searchText(input.search, 'Search'); const args = [identity.organization_id];
  const conditions = ['field.organization_id=$1', 'field.active'];
  const bind = (value) => { args.push(value); return `$${args.length}`; };
  if (search) {
    const match = bind(literalSearch(search));
    conditions.push(`(${Object.entries(listColumns).filter(([key]) => key !== 'created_at').map(([, column]) => `${column} ILIKE ${match}`).join(' OR ')})`);
  }
  const filters = input.filters ?? {}; fieldsOnly(filters, Object.keys(listColumns));
  for (const [key, filter] of Object.entries(filters)) {
    fieldsOnly(filter, key === 'created_at' ? ['type', 'from', 'to'] : ['type', 'value']);
    if (key === 'created_at') {
      if (filter.type !== 'date') throw new HttpError(400, 'invalid_filter', 'Created At requires a date range.');
      const { start, before } = customFieldDateRange(filter);
      if (start) conditions.push(`field.created_at>=${bind(start)}`);
      if (before) conditions.push(`field.created_at<${bind(before)}`);
    } else if (key === 'data_type') {
      if (filter.type !== 'select') throw new HttpError(400, 'invalid_filter', 'Data Type requires a selection.');
      if (filter.value != null && filter.value !== '') {
        if (!customFieldTypes.some((type) => type.value === filter.value)) throw new HttpError(400, 'invalid_filter', 'Data Type is invalid.');
        conditions.push(`field.field_type=${bind(filter.value)}`);
      }
    } else {
      if (filter.type !== 'text') throw new HttpError(400, 'invalid_filter', 'Custom field filters require text.');
      const value = searchText(filter.value, 'Filter');
      if (value) conditions.push(`${listColumns[key]} ILIKE ${bind(literalSearch(value).replace(/\s+/g, '%'))}`);
    }
  }
  const sort = input.sort;
  if (sort) {
    fieldsOnly(sort, ['key', 'dir']);
    if (!Object.hasOwn(listColumns, sort.key) || !['asc', 'desc'].includes(sort.dir)) throw new HttpError(400, 'invalid_sort', 'Sort column or direction is invalid.');
  }
  const order = sort ? `${listColumns[sort.key]} ${sort.dir} NULLS LAST` : 'field.created_at DESC';
  const from = `FROM custom_field_definitions field WHERE ${conditions.join(' AND ')}`;
  const totalCount = (await client.query(`SELECT count(*)::integer AS total ${from}`, args)).rows[0].total;
  const rows = (await client.query(`SELECT field.id AS _id,field.revision,field.label,field.description,field.key,field.associated_with,
    field.scheme,field.field_type AS data_type,field.created_at ${from} ORDER BY ${order},field.id DESC LIMIT $${args.length + 1} OFFSET $${args.length + 2}`,
  [...args, pageSize, (page - 1) * pageSize])).rows;
  return { rows, totalCount };
}

export async function customFieldRoles(client, identity, input = {}) {
  requireRead(identity); fieldsOnly(input, ['search']);
  const search = searchText(input.search, 'Role search');
  const rows = (await client.query(`SELECT id,name FROM roles WHERE organization_id=$1 AND name ILIKE $2 ORDER BY name,id LIMIT 101`,
    [identity.organization_id, literalSearch(search)])).rows;
  return { rows: rows.slice(0, 100), hasMore: rows.length > 100 };
}

export async function masterCustomFieldUsers(client, identity, input = {}) {
  requireRead(identity); fieldsOnly(input, ['search']);
  const search = searchText(input.search, 'User search');
  // RelationSelect searches its displayed label after replacing separators and JavaScript whitespace.
  const labelSpacing = '[_/\u0009\u000a\u000b\u000c\u000d \u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000\ufeff-]+';
  // The source GenericForm user selector includes inactive members too.
  const rows = (await client.query(`SELECT user_id AS id,display_name AS name FROM method_access_user_labels
    WHERE organization_id=$1 AND (display_name ILIKE $2 OR regexp_replace(display_name,$3,' ','g') ILIKE $2)
    ORDER BY display_name,user_id LIMIT 101`,
  [identity.organization_id, literalSearch(search), labelSpacing])).rows;
  return { rows: rows.slice(0, 100), hasMore: rows.length > 100 };
}
