'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import FormElement from '../ui/FormElement.jsx';
import Checkbox from '../ui/Checkbox.jsx';
import SearchableSelect from '../ui/SearchableSelect.jsx';
import AppIcon from '../ui/AppIcon.jsx';
import PrimaryButton from '../ui/PrimaryButton.jsx';
import SecondaryButton from '../ui/SecondaryButton.jsx';
import { showToast } from '../ui/toast.jsx';
import { apiRequest } from '../../lib/api-client.js';
import { customFieldInput } from '../../masters/custom-field-input.js';
import { customFieldTypes, customFieldAssociations, customFieldLegacyAssociations, customFieldDateFormats,
  customFieldDateTimeFormats, customFieldGenerationTimes } from '../../masters/custom-field-config.js';

export const customFieldFormFields = [
  { name: 'label', label: 'Label', required: true, maxLength: 200, placeholder: 'Add label of the field', helper: 'Display label shown to users. This can be human readable.' },
  { name: 'description', label: 'Description', type: 'textarea', maxLength: 16000, placeholder: 'Add Description of the field', helper: 'Description on what is the field. This is for your reference and wont be visible to the end user' },
  { name: 'key', label: 'Key', required: true, maxLength: 150, placeholder: 'field_key', helper: 'Saved field key. Use letters, numbers, and "_" only. No spaces.' },
  { name: 'autoGenerated', label: 'Source', maxLength: 250, placeholder: 'Source' },
  { name: 'scheme', label: 'Scheme', maxLength: 5000, placeholder: 'Scheme', helper: 'Use {{entity.field_name}} to include a field from the associated entity.' },
  { name: 'nablDisplayTerm', label: 'NABL Term', maxLength: 250, placeholder: 'NABL Term' },
  { name: 'nonNablDisplayTerm', label: 'NON-NABL Term', maxLength: 250, placeholder: 'NON-NABL Term' },
  { name: 'showInList', label: 'Show in List', type: 'boolean', helper: 'Enabling this will mean it shows up in the listing page.' },
  { name: 'showInFilter', label: 'Show in Filter', type: 'boolean', helper: 'Enabling this will mean it shows up in the filter of listing page.' },
  { name: 'allowsMultiple', label: 'Multiple', type: 'boolean', helper: 'Enabling this will mean it You can add multiple rows of this' },
  { name: 'isRequired', label: 'Mandatory?', type: 'boolean', helper: 'Enabling this will mean that this field is mandatory' },
  { name: 'paddedNumber', label: 'Padded Number', type: 'number', min: 0, max: 1000, placeholder: 'Scheme', helper: 'Number of leading padding characters. Use 3 to generate values like 0001.' },
  { name: 'displayOrder', label: 'Order Index', type: 'number', min: 0, max: 100000, placeholder: 'Column Order in Listing', helper: 'This number determines the order of the column' },
  { name: 'fieldType', label: 'Data Type', type: 'select', options: customFieldTypes, helper: 'The data type of the input expected' },
  { name: 'dateFormat', label: 'Date Format', type: 'select', options: customFieldDateFormats, showWhen: ['fieldType', 'date'], helper: 'Display format used for this date field.' },
  { name: 'datetimeFormat', label: 'Date-Time Format', type: 'select', options: customFieldDateTimeFormats, showWhen: ['fieldType', 'date_time'], helper: 'Display format used for this date-time field.' },
  { name: 'options', label: 'Dropdown Options', type: 'options', showWhen: ['fieldType', 'select'], helper: 'Used when Data Type is Dropdown/Select. Key is saved; label is shown to users.' },
  { name: 'associatedWith', label: 'Associated With', type: 'select', required: true, options: customFieldAssociations, helper: 'What entity should this field be associated with' },
  { name: 'generatedAt', label: 'Generated At', type: 'select', options: customFieldGenerationTimes, helper: 'When should the value for this field be generated. On Demand means you will get a button in work mode and on initiation means when the entity is created' },
  { name: 'associateRoleSpecificUsers', label: 'Associate Role Specific Users?', type: 'boolean', showWhen: ['fieldType', 'multi_user_select'] },
  { name: 'associatedWithRoleId', label: 'Associate Role', type: 'role', showWhen: ['associateRoleSpecificUsers', true] },
  { name: 'roleIdsCanEdit', label: 'Roles', type: 'role', multiple: true, helper: 'The list of roles that can edit this value at various stages' },
  { name: 'splitter', label: 'Splitter Character', maxLength: 20, placeholder: 'Splitter Character', helper: 'The character used to split values' },
  { name: 'filterSearchType', label: 'Filter Search Type', maxLength: 40, placeholder: 'Filter Search Type', helper: 'text/dropdown based on what we want in index filter' },
  { name: 'showInDashboard', label: 'Show in Dashboard', type: 'boolean', helper: 'Enabling this displays the dropdown of this field in Dashboard' },
  { name: 'showInReport', label: 'Show in Report', type: 'boolean', helper: 'Enabling this displays the dropdown of this field in Report' },
  { name: 'validateUniqueness', label: 'Validate Uniqueness?', type: 'boolean' },
  { name: 'hideFromSampleCreation', label: 'Hide From Sample Creation?', type: 'boolean' },
  { name: 'editOnReissue', label: 'Editable On Report Reissue?', type: 'boolean', showWhen: ['associatedWith', ['sample', 'sample_product']],
    helper: 'Enabling this lets the value be changed while reissuing a finalised report.' },
];

const roleOption = (row) => ({ value: row.id, label: String(row.name ?? row.id).replace(/[_/-]/g, ' ').replace(/\s+/g, ' ').trim() });
function RoleField({ config, value, selectedRoles, disabled, onChange }) {
  const [options, setOptions] = useState(() => selectedRoles.map(roleOption));
  const [error, setError] = useState(''); const [hasMore, setHasMore] = useState(false); const query = useRef(null);
  useEffect(() => () => query.current?.abort(), []);
  const loadOptions = useCallback(async (search) => {
    query.current?.abort(); const controller = new AbortController(); query.current = controller;
    try {
      const result = await apiRequest(`/api/masters/project-fields/roles?search=${encodeURIComponent(search)}`, { signal: controller.signal });
      if (controller.signal.aborted) return [];
      setError(''); setHasMore(result.hasMore); return result.rows.map(roleOption);
    } catch (failure) {
      if (!controller.signal.aborted) { setError(failure.message); setHasMore(false); }
      return [];
    }
  }, []);
  const id = `custom-field-${config.name}`;
  return <div className="mb-3 smplfy-form-element">
    <div className="smplfy-form-element__label-row"><label className="smplfy-form-element__label" htmlFor={id}>{config.label}</label></div>
    <SearchableSelect id={id} name={config.name} value={value} options={options} loadOptions={loadOptions} cacheOptions={false}
      multiple={config.multiple} clearable disabled={disabled} invalid={Boolean(error)} placeholder={`Select ${config.label}`}
      aria-describedby={[config.helper && `${id}-help`, error && `${id}-error`, hasMore && `${id}-more`].filter(Boolean).join(' ') || undefined}
      noOptionsMessage={error ? 'Roles could not be loaded. Try searching again.' : 'No options found'}
      onChange={(next, selected) => {
        const choices = config.multiple ? selected ?? [] : selected ? [selected] : [];
        onChange(next, choices.map((option) => ({ id: option.value, name: option.label }))); setOptions(choices);
      }} />
    {config.helper ? <div id={`${id}-help`} className="smplfy-form-text form-text">{config.helper}</div> : null}
    {hasMore ? <div id={`${id}-more`} className="smplfy-form-text form-text">More roles match. Refine your search to find a role.</div> : null}
    {error ? <div id={`${id}-error`} className="smplfy-form-element__message smplfy-form-element__message--error" role="alert">{error}</div> : null}
  </div>;
}

function OptionsField({ config, options, disabled, error, onChange }) {
  return <div className="mb-3">
    <div className="d-flex align-items-center gap-2 mb-2"><span className="smplfy-form-label form-label mb-0">Dropdown Options</span>
      <button type="button" className="btn btn-sm btn-success" aria-label="Add Option" disabled={disabled || options.length >= 500}
        onClick={() => onChange([...options, { id: crypto.randomUUID(), key: '', label: '' }])}><AppIcon name="plus" size={12} /></button>
    </div>
    <div className="smplfy-form-text form-text mb-2">{config.helper}</div>
    {!options.length ? <div className="border rounded bg-light px-3 py-2 text-muted small">No dropdown options added.</div> : options.map((option, index) =>
      <div className="row g-2 align-items-center mb-2" key={option.id}>
        <div className="col-md-4"><FormElement inputProps={{ id: `option-${option.id}-key`, name: `options-${index}-key`, 'aria-label': `Option ${index + 1} key`, placeholder: 'option_key',
          value: option.key, maxLength: 150, disabled, onChange: (event) => onChange(options.map((entry) => entry.id === option.id ? { ...entry, key: event.target.value } : entry)) }} /></div>
        <div className="col-md-7"><FormElement inputProps={{ id: `option-${option.id}-label`, name: `options-${index}-label`, 'aria-label': `Option ${index + 1} label`, placeholder: 'Option label',
          value: option.label, maxLength: 200, disabled, onChange: (event) => onChange(options.map((entry) => entry.id === option.id ? { ...entry, label: event.target.value } : entry)) }} /></div>
        <div className="col-auto"><button type="button" className="btn btn-sm btn-danger" aria-label={`Remove row ${index + 1}`} disabled={disabled}
          onClick={() => onChange(options.filter((entry) => entry.id !== option.id))}><AppIcon name="trash" size={13} /></button></div>
      </div>)}
    {error ? <div className="smplfy-form-element__message smplfy-form-element__message--error">{error}</div> : null}
  </div>;
}

export default function CustomFieldForm({ field }) {
  const router = useRouter(); const search = useSearchParams(); const newId = useRef(null); const saveRequest = useRef(null); const busy = useRef(false);
  const [draft, setDraft] = useState(() => Object.fromEntries(customFieldFormFields.map((config) => [config.name,
    field?.[config.name] ?? (config.type === 'boolean' ? false : config.multiple || config.type === 'options' ? [] : '')])));
  const [roleLabels, setRoleLabels] = useState(() => [...(field?.editRoles ?? []), ...(field?.associatedWithRoleId ? [{ id: field.associatedWithRoleId, name: field.associatedWithRoleName }] : [])]);
  const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [fieldErrors, setFieldErrors] = useState({});
  const from = search.get('from'); const returnPath = from && /^\/project_fields(?:\?[^#]*)?$/.test(from) ? from : '/project_fields';
  function change(name, value) {
    setDraft((current) => ({ ...current, [name]: value }));
    setFieldErrors((current) => { const { [name]: _error, ...rest } = current; return rest; });
  }
  async function save(event) {
    event.preventDefault(); if (busy.current) return;
    setError(''); const problems = {};
    for (const config of customFieldFormFields.filter((config) => config.required)) if (!String(draft[config.name] ?? '').trim()) problems[config.name] = `${config.label} is required.`;
    if (draft.key.trim() && !/^[A-Za-z0-9_]+$/.test(draft.key.trim())) problems.key = 'Key can only contain letters, numbers, and underscores. Spaces are not allowed.';
    setFieldErrors(problems); if (Object.keys(problems).length) { showToast(Object.values(problems)[0], 'error'); return; }
    newId.current ??= crypto.randomUUID(); const id = field?.id ?? newId.current;
    let body;
    try {
      const { requestId: _requestId, ...normalized } = customFieldInput({ ...draft, id, revision: field?.revision ?? 0, requestId: id, lookupSourceId: field?.lookupSourceId ?? null,
        options: draft.options.filter((option) => option.key.trim() || option.label.trim()) });
      body = normalized;
    } catch (failure) { setError(failure.message); showToast(failure.message, 'error'); return; }
    const content = JSON.stringify(body);
    if (saveRequest.current?.content !== content) saveRequest.current = { content, id: crypto.randomUUID() };
    busy.current = true; setSaving(true);
    try {
      await apiRequest('/api/masters/project-fields', { method: 'POST', body: { ...body, requestId: saveRequest.current.id } });
      router.push(returnPath);
    } catch (failure) { setError(failure.message); showToast(failure.message, 'error'); busy.current = false; setSaving(false); }
  }
  return <div className="container-fluid py-4"><div className="row justify-content-center"><div className="col-xl-7 col-lg-9">
    <div className="card border-0 shadow-sm"><div className="card-body p-4"><form onSubmit={save} noValidate>
      {error ? <div className="alert alert-danger" role="alert">{error}</div> : null}
      {customFieldFormFields.map((config) => {
        if (config.showWhen) {
          const [name, expected] = config.showWhen;
          if (Array.isArray(expected) ? !expected.includes(draft[name]) : draft[name] !== expected) return null;
        }
        const value = draft[config.name]; const id = `custom-field-${config.name}`;
        if (config.type === 'boolean') return <div key={config.name}>
          <div className="mb-3"><div className="smplfy-checkbox-field"><Checkbox id={id} name={config.name} checked={value}
            disabled={saving} ariaLabel={config.label} onChange={(value) => change(config.name, value)} />
            <div className="smplfy-checkbox-field__body"><label className="smplfy-checkbox-field__label mb-0" htmlFor={id}>{config.label}</label></div>
          </div></div>
          {config.helper ? <div className="smplfy-form-text form-text mb-3">{config.helper}</div> : null}
        </div>;
        if (config.type === 'options') return <OptionsField key={config.name} config={config} options={value} disabled={saving}
          error={fieldErrors.options} onChange={(value) => change(config.name, value)} />;
        if (config.type === 'role') return <RoleField key={config.name} config={config} value={value} disabled={saving}
          selectedRoles={roleLabels.filter((role) => (Array.isArray(value) ? value : [value]).includes(role.id))}
          onChange={(value, labels) => { change(config.name, value); setRoleLabels((current) => [...current.filter((role) => !labels.some((next) => next.id === role.id)), ...labels]); }} />;
        let options = config.options;
        if (config.name === 'associatedWith' && customFieldLegacyAssociations.some((option) => option.value === field?.associatedWith)) {
          options = [...customFieldAssociations, ...customFieldLegacyAssociations.filter((option) => option.value === field.associatedWith)];
        }
        return <div className="mb-3" key={config.name}><FormElement type={config.type === 'select' ? 'dropdown' : config.type === 'textarea' ? 'textarea' : 'text'}
          label={config.label} mandatory={config.required} helperText={config.helper} message={fieldErrors[config.name]} messageTone="error"
          inputProps={{ id, name: config.name, type: config.type === 'number' ? 'number' : undefined, value, options, placeholder: config.placeholder,
            maxLength: config.maxLength, min: config.min, max: config.max, rows: config.type === 'textarea' ? 3 : undefined,
            disabled: saving, onChange: (event) => change(config.name, event.target.value) }} /></div>;
      })}
      <div className="d-flex gap-2 justify-content-end mt-4"><SecondaryButton type="button" leftIcon="close" disabled={saving} onClick={() => router.push(returnPath)}>Cancel</SecondaryButton>
        <PrimaryButton type="submit" leftIcon="save" disabled={saving}>{saving ? 'Saving...' : field ? 'Update' : 'Create'}</PrimaryButton></div>
    </form></div></div>
  </div></div></div>;
}
