import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { customFieldInput } from '../../src/masters/custom-field-input.js';
import { customFieldTypes, customFieldDateFormats, customFieldDateTimeFormats } from '../../src/masters/custom-field-config.js';

const input = (changes = {}) => ({ id: randomUUID(), requestId: randomUUID(), revision: 0, label: 'Synthetic field', key: 'MiXeD_Key', associatedWith: 'product', ...changes });
const option = (key = 'A', label = 'First') => ({ id: randomUUID(), key, label });

test('report reissue editability defaults false and retains explicit booleans on hidden associations', () => {
  assert.equal(customFieldInput(input()).editOnReissue, false);
  for (const associatedWith of ['sample', 'sample_product', 'product', 'users']) {
    for (const editOnReissue of [true, false]) {
      assert.equal(customFieldInput(input({ associatedWith, editOnReissue })).editOnReissue, editOnReissue);
    }
  }
  for (const editOnReissue of [null, 'true', 'false', 0, 1, {}, []]) {
    assert.throws(() => customFieldInput(input({ editOnReissue })), { status: 400 });
  }
});

test('custom fields preserve source defaults, normalized keys, false flags, zero text and explicit zero order', () => {
  const value = customFieldInput(input({ label: '  Label  ', description: ' 0\n ', autoGenerated: ' 0 ', splitter: '', displayOrder: 0, paddedNumber: '0' }));
  assert.equal(value.key, 'mixed_key'); assert.equal(value.label, 'Label'); assert.equal(value.description, '0'); assert.equal(value.autoGenerated, '0');
  assert.equal(value.splitter, '/'); assert.equal(value.displayOrder, 0); assert.equal(value.paddedNumber, 0); assert.equal(value.isRequired, false);
  const defaults = customFieldInput(input());
  assert.equal(defaults.fieldType, 'text'); assert.equal(defaults.displayOrder, 10000); assert.equal(defaults.generatedAt, 'on_init');
  assert.equal(defaults.associatedWithRoleId, null); assert.deepEqual(defaults.roleIdsCanEdit, []); assert.deepEqual(defaults.options, []);
});

test('custom field authoring accepts every displayed type and retains hidden options and role settings', () => {
  const options = [option('A', 'Upper'), option('a', 'Lower')]; const roleId = randomUUID();
  for (const { value: fieldType } of customFieldTypes) {
    const value = customFieldInput(input({ fieldType, options, roleIdsCanEdit: [roleId], associatedWithRoleId: roleId, associateRoleSpecificUsers: true }));
    assert.equal(value.fieldType, fieldType); assert.deepEqual(value.options, options); assert.equal(value.associatedWithRoleId, roleId);
    assert.deepEqual(value.roleIdsCanEdit, [roleId]); assert.equal(value.associateRoleSpecificUsers, true);
  }
});

test('date formats match the source choices, default invalid formats and clear formats on other types', () => {
  for (const { value: dateFormat } of customFieldDateFormats) assert.equal(customFieldInput(input({ fieldType: 'date', dateFormat })).dateFormat, dateFormat);
  for (const { value: datetimeFormat } of customFieldDateTimeFormats) assert.equal(customFieldInput(input({ fieldType: 'date_time', datetimeFormat })).datetimeFormat, datetimeFormat);
  assert.equal(customFieldInput(input({ fieldType: 'date', dateFormat: 'wrong' })).dateFormat, 'DD/MM/YYYY');
  assert.equal(customFieldInput(input({ fieldType: 'date_time', datetimeFormat: 'wrong' })).datetimeFormat, 'DD/MM/YYYY HH:mm:ss');
  const value = customFieldInput(input({ dateFormat: 'YYYY-MM-DD', datetimeFormat: 'YYYY-MM-DD HH:mm' }));
  assert.equal(value.dateFormat, ''); assert.equal(value.datetimeFormat, '');
});

test('option and role identity stays ordered, normalized and distinct without folding option keys', () => {
  const first = option(); const second = option('a', 'Second'); const role = randomUUID(); const other = randomUUID();
  const value = customFieldInput(input({ options: [second, { ...first, id: first.id.toUpperCase() }], roleIdsCanEdit: [other, role.toUpperCase()] }));
  assert.deepEqual(value.options, [second, first]); assert.deepEqual(value.roleIdsCanEdit, [other, role]);
  for (const options of [[first, { ...first, key: 'B' }], [first, { ...option(), key: 'A' }], null, {}, '', [option('a b')], [option('A', '')]]) {
    assert.throws(() => customFieldInput(input({ options })), { status: 400 });
  }
  for (const roleIdsCanEdit of [[role, role.toUpperCase()], null, '', {}, ['invalid']]) assert.throws(() => customFieldInput(input({ roleIdsCanEdit })), { status: 400 });
});

test('finite fractional metadata is retained while invalid numbers and oversized counts are rejected', () => {
  const value = customFieldInput(input({ paddedNumber: 1.5, displayOrder: '2.25' }));
  assert.equal(value.paddedNumber, 1.5); assert.equal(value.displayOrder, 2.25);
  for (const paddedNumber of [true, {}, ' ', NaN, Infinity, -1, 1000.1, '12x']) assert.throws(() => customFieldInput(input({ paddedNumber })), { status: 400 });
  for (const displayOrder of [false, [], NaN, -Infinity, -0.1, 100001]) assert.throws(() => customFieldInput(input({ displayOrder })), { status: 400 });
  const options = Array.from({ length: 500 }, (_, index) => option(`v${index}`));
  assert.equal(customFieldInput(input({ options })).options.length, 500);
  assert.throws(() => customFieldInput(input({ options: [...options, option('extra')] })), { status: 400 });
  const roleIdsCanEdit = Array.from({ length: 500 }, () => randomUUID());
  assert.equal(customFieldInput(input({ roleIdsCanEdit })).roleIdsCanEdit.length, 500);
  assert.throws(() => customFieldInput(input({ roleIdsCanEdit: [...roleIdsCanEdit, randomUUID()] })), { status: 400 });
});

test('custom field input rejects excluded associations, unknown types, malformed text and hidden storage payloads', () => {
  for (const changes of [{ associatedWith: 'project' }, { associatedWith: 'custom_form' }, { associatedWith: 'document' }, { associatedWith: '' },
    { fieldType: 'arbitrary' }, { fieldType: false }, { fieldType: null }, { generatedAt: false }, { generatedAt: 'later' },
    { label: '' }, { label: 'x'.repeat(201) }, { label: '\0' }, { description: false }, { description: 'x'.repeat(16001) },
    { key: 'x'.repeat(151) }, { key: 'with space' }, { key: 'é' }, { key: 'a.b' }, { scheme: 'x'.repeat(5001) },
    { splitter: 'x'.repeat(21) }, { nablDisplayTerm: 'x'.repeat(251) }, { filterSearchType: 'x'.repeat(41) },
    { showInList: 'false' }, { isRequired: null }, { associatedWithRoleId: 'bad' }, { revision: 0.5 }, { revision: -1 },
    { id: 'bad' }, { requestId: null }, { revision: 2_147_483_647 }, { data: {} }, { dataMasterId: randomUUID() }, { active: false }]) {
    assert.throws(() => customFieldInput(input(changes)), { status: 400 });
  }
  assert.equal(customFieldInput(input({ key: 'A'.repeat(150) })).key.length, 150);
});
